#pragma once
#include <cstring>
#include <string>
#include <vector>
#include "types.hpp"

// Forward declarations
std::string utf8CharsToString(const std::vector<Utf8Char>& chars);
void convertStringToUtf8Chars(const std::string& str, std::vector<Utf8Char>& chars);
bool isKeyCharacter(const Utf8Char& c);

namespace NookCodes {
	struct CodePair {
		const char* name;
		const char* code;
	};

	const CodePair codes[] = {
		// Furniture
		{"blue bed", "b2sF3GjWFEH&%xGk3o2ozwpvqApc"},
		{"blue bench", "b2sF3hVgFUH&%xGkwo2ozwpvqApc"},
		{"blue bookcase", "IhRFm5hubzGaqxG%Rucdh5HDrQpk"},
		{"blue bureau", "@PYIwZdBRcwv@Q28Y56PVnqHegTU"},
		{"blue cabinet", "@AZIwZdB7cwv@Q28Y5yPVnqpegTU"},
		{"blue chair", "HMjThl&e#bwhZzwQ&2UyxrlbvId%"},
		{"blue clock", "l@sk6WCWWD2ONl2fB3TmNs4e&Cpi"},
		{"blue dresser", "HJjTha7e#cwhZzwQ&2UyErlovId%"},
		{"blue table", "2yoF3hVgFMi&%xGkwo2nXrJvqBpc"},
		{"blue wardrobe", "MA5Iwydn7cG9@Q7ijb6PRncHtgCU"},
		{"cabana armchair", "9dO4LxSfatjcFkQEjNtiwcCLECfP"},
		{"cabana bed", "hOu6RFEi6UFx8DyGetV#iDmujoxY"},
		{"cabana bookcase", "l@skLWOfWD2ONd2XV3WmXsAeRm2i"},
		{"cabana chair", "lEskIWCWWD2ONapXV3Am@s4tRm2i"},
		{"cabana dresser", "MAzIRydn7cr9@Q7ijbyPRncPtgC@"},
		{"cabana lamp", "JTmu7GJH3Eo#FYxDSynaCx#PaWge"},
		{"cabana screen", "JTmu3Z2H3Jo#FYxDeynaCRVIaWge"},
		{"cabana table", "lEskIWCWWD2OUapXV3Am@s4tRC2i"},
		{"cabana vanity", "JTmuEMp43fuiFYxmHynaCx#PaWge"},
		{"cabana wardrobe", "@PYIwZdBRcw9@Q2NY56PRncHtgTU"},
		{"cabin armchair", "IysFm5hubYGaqxG%Ruclj5H@rQpk"},
		{"cabin bed", "PJjThj7V#cwjZzwQ&2U6ErlovId%"},
		{"cabin bookcase", "b2sF3hjWFEH&%xGk3o2kzwpvqApc"},
		{"cabin chair", "JTmu&GJ43EuiFYxmpynaCxeIaWge"},
		{"cabin clock", "AMjThj7V#KwjZzwQ&2NZTrdbvId%"},
		{"cabin couch", "hhRFmijgbKGjqxG%RuWoG5jDrQpk"},
		{"cabin dresser", "MAzIwydn7Yr9@Q7ijblPgocIYgC@"},
		{"cabin low table", "TJjTha7e#qwhZzwQ&2N5frdovId%"},
		{"cabin table", "JTmu7GJH3Eo#FYxDSynaCx#IaWge"},
		{"cabin wardrobe", "@PYIwZdBRYwv@Q28Y5lPgnqpxgTU"},
		{"classic bed", "MHmu%Z75cJuiFYx7nnnaCRxHaWge"},
		{"classic cabinet", "rFM4L#tfEjSaHkfww%dCBuEdjpft"},
		{"classic chair", "MA5Iwydn7cG9@Q7ijb6PRncptgCU"},
		{"classic clock", "hOu6jhEN6UFC8Dby@jvDuS7ujoxY"},
		{"classic desk", "@PYIwZdBRcwv@Q28Y56PVnqpegTU"},
		{"classic hutch", "@AZIwZdB7Ywv@Q28Y5lP7nqpxgTU"},
		{"classic sofa", "9qO4IVSfat23FkQ#jitimcCQqCft"},
		{"classic table", "hOu6RFEi6UFt8DcG@Hv#zHOuz8xY"},
		{"classic vanity", "@AZIwZdB7cw9@Q2NY56PVncptgTU"},
		{"classic wardrobe", "@AZIRZdB7Yw9@Q2NY5dPgncHYgTU"},
		{"exotic bed", "JTmu3Z2H3Jo#FYxDeynaCRxPaWge"},
		{"exotic bench", "pysFmzhgbYGjqxG%Ruclj5H@rQpk"},
		{"exotic bureau", "MAzIRydn7Yr9@Q7ijbdPgocIYgC@"},
		{"exotic chair", "l7RuzM2WhCsL&jBAmn8tQ5INFDDp"},
		{"exotic chest", "AJjThj7V#KwjZzwQ&2N5frdovId%"},
		{"exotic end table", "l@skLWOfWD2OUd2fB3WmXsAe&Cpi"},
		{"exotic lamp", "HJjThl&e#bwhZzwQ&2UyErlovId%"},
		{"exotic screen", "bnoF3hVgFUi&%xGkwo2k5wpvqBpc"},
		{"exotic table", "TMjThl&e#qwhZzwQ&2NZTrdbvId%"},
		{"exotic wardrobe", "@AZIwZdB7Ywv@Q28Y5dPgnqpxgTU"},
		{"green bed", "PMjThj7V#bwjZzwQ&2U6xrlbvId%"},
		{"green bench", "2hsF3hjWFrH&%xGk3o2nirJvqApc"},
		{"green chair", "sysFmXjubKGaqxG%RuWkV5j@rQpk"},
		{"green counter", "2yoF3hVgFri&%xGkwo2nXrJvqBpc"},
		{"green desk", "JTmu3MpH3fo#FYxD2ynaCxePaWge"},
		{"green dresser", "@PYIRZdBRYwv@Q28Y5dPgnqHxgTU"},
		{"green lamp", "b2sF3GVgFUH&%xGkwo2ozwpvqApc"},
		{"green pantry", "PJjThj7V#bwjZzwQ&2U6ErlovId%"},
		{"green table", "hhRFmzhgbKGjqxG%RuWkG5jDrQpk"},
		{"green wardrobe", "@PYIRZdBRYw9@Q2NY5dP7ncHYgTU"},
		{"kiddie bed", "rV96QaVULqQ%txurfXwDgIv2aKqu"},
		{"kiddie bookcase", "rge6QaVNLEQ4txh5fXV@gmv2dzqu"},
		{"kiddie bureau", "MA5IRydn7YG9@Q7ijblPgncpYgCU"},
		{"kiddie chair", "faHCIuxyxqLs#Ath6n44rDGOKTn@"},
		{"kiddie clock", "#Ve6QvVULqQkexu5fXVDemv2qzqu"},
		{"kiddie couch", "zV96QvVULEIDexurfXwDe9v2aKlu"},
		{"kiddie dresser", "@AZIRZdB7cw9@Q2NY56PRncHtgTU"},
		{"kiddie stereo", "TaHCpXxhxELs#Aty6n44UDwOKTl@"},
		{"kiddie table", "rV96QaVULEIktxu5fXVDgmv2qzqu"},
		{"kiddie wardrobe", "@PYIRZdBRcw9@Q2NY5yPVncHtgTU"},
		{"lovely armchair", "rFM4L#eWfjpaHkqxw%dCBuEdjpft"},
		{"lovely armoire", "MAzIwydn7cr9@Q7ijbyPRncItgC@"},
		{"lovely bed", "9qO4IVSfat23FkQUjitimcCQqCft"},
		{"lovely chair", "hOu6R2EN6UFC8DyyetVPzPnuz8xY"},
		{"lovely dresser", "MA5Iwydn7cG9@Q7ijbyPVncHtgCU"},
		{"lovely end table", "rWM46PeWfjp&Hkq#wAdCYuElRFfP"},
		{"lovely kitchen", "hOu6jpEi6UFe8DbG@jvUuSmujoxY"},
		{"lovely lamp", "hOu6RFEi6UFx8D5GetV#iDmujoxY"},
		{"lovely table", "IaBARFi#KAQtESDS9cQQyvUZPT7N"},
		{"lovely vanity", "hOu6jpEi6UFt8DbG@jvUbHOuz8xY"},
		{"modern bed", "d7RuzMgghVsL&jBAkn8YZ5QNFDDp"},
		{"modern cabinet", "d7RuzM2WhVsL&jBAmn8YZ5QNFDDp"},
		{"modern chair", "l@skLWOfWD2OUd2XV3WmXsAeRO2i"},
		{"modern desk", "lnRuzQ2WhCQL&jBAmn8BA5INFUDp"},
		{"modern dresser", "@AZIRZdB7Yw9@Q2NY5lP7ncpYgTU"},
		{"modern end table", "l@sk6WOfWD2ONl2XV3TmNs4eRC2i"},
		{"modern lamp", "nN#PkV&ugrUcBzvMt8hww&vg#Djf"},
		{"modern sofa", "b2sF3GVgFUH&%xGkwo2kzwpvqApc"},
		{"modern table", "AJjThj7V#qwjZzwQ&2NZfrdovId%"},
		{"modern wardrobe", "MAzIRydn7cr9@Q7ijb6PVncItgC@"},
		{"ranch armchair", "rWM4L#tfEjp&Hkf3wAdCYuEljpft"},
		{"ranch bed", "9dO4LxSfatjcFkQxjNtiwcCLECfP"},
		{"ranch bookcase", "rWM4L#tfEjp&HkfEwAdCYuEljpft"},
		{"ranch chair", "hOu6jhEN6UFC8D5yeBVDbPnuz8xY"},
		{"ranch couch", "hOu6jhEN6UF38D5yeBVDbPnuz8xY"},
		{"ranch dresser", "MA5IRydn7cG9@Q7ijb6PRncptgCU"},
		{"ranch hutch", "hOu6RFEi6UFt8DbG@Hv#iSmujoxY"},
		{"ranch table", "rFM46PtfEjSaHkf3w%dCBuEdRFfP"},
		{"ranch tea table", "hOu6RFEi6UFe8DbG@Hv#zHOuz8xY"},
		{"ranch wardrobe", "MAzIwydn7Yr9@Q7ijblP7ncIYgC@"},
		{"regal armoire", "MA5IRydn7cG9@Q7ijb6PVocptgCU"},
		{"regal bed", "JTmu&GJ43EuiFYxmSynaCx#PaWge"},
		{"regal bookcase", "hOu6jhEN6UFc8Dby@jvDuS7ujoxY"},
		{"regal chair", "rFM46PeWfjpaHkqEw%dCBuEdRFfP"},
		{"regal cupboard", "hOu6jhEN6UFO8D5yeBVDbPnuz8xY"},
		{"regal dresser", "MAzIwydn7Yr9@Q7ijbdPgocIYgC@"},
		{"regal lamp", "JTmu&yF43MuiFYxm@ynaCRxPaWge"},
		{"regal sofa", "JTmu3MpH3fo#FYxDHynaCxeIaWge"},
		{"regal table", "hOu6jhEN6UFC8DyyeBVDbPnuz8xY"},
		{"regal vanity", "JTmu3MpH3fo#FYxDpynaCxePaWge"},
		{"harvest bed", "IL&DL%A&wobiIF#x7Z@WMho3@#ER"},
		{"harvest bureau", "rge9QKGNLqQ4txa5fXj@2mv2dz%u"},
		{"harvest chair", "LKTQmrP38A%gKYUqKjaqkjxVJwQ2"},
		{"harvest clock", "PUqIYr2eDxcr5iRBvEqjjBh#MZM2"},
		{"harvest dresser", "5g99QKGNLEQQtxarfXu@29v2Kz&u"},
		{"harvest lamp", "PUcIAr2#DR3r5iRBvElYRVXiMZMa"},
		{"harvest mirror", "fapFIuAyxqLw#AOs6nz4LDGOKTnv"},
		{"harvest sofa", "&r&DQf%&w4O4IF#x7ZD2Jy&w@PYR"},
		{"harvest table", "IL&DL%A&sobiIm#x7Z@WMy83@#xR"},
		{"harvest tv", "Ir&DL%A&s4biIm#x7ZD2Qh73@PxR"},
		{"jingle bed", "zV96QvVULEQDexurfXwDe9v2aKlu"},
		{"jingle chair", "zge6QvVNLqQAexh5fXV@eCv2dzlu"},
		{"jingle clock", "#g96QvVNLqI4exh5fXV@emv2dzqu"},
		{"jingle dresser", "MA5IRydn7YG9@Q7ijbdPgncpYgCU"},
		{"jingle lamp", "TapCpuxhxlLs#Aty6o44U@wOKTl@"},
		{"jingle piano", "fapCpXxhxEss#Ath6n44rDGOKTn@"},
		{"jingle shelves", "#g96QvVNLEI4exh5fXV@emv2dzqu"},
		{"jingle sofa", "fapCpuxhxv4s#Ath6o44r@GOKTn@"},
		{"jingle table", "zVe6QvVULEQmexu5fXVDeCv2qzlu"},
		{"jingle wardrobe", "MAzIRydn7Yr9@Q7ijblPgncPYgC@"},
		{"snowman bed", "Wb5Q%t&VxJuZnYlOAl8owl7JRvpF"},
		{"snowman chair", "nN#P3V&uu9UcBzvMt8Jws&v7#Djf"},
		{"snowman clock", "kb5Qfd&RxJuZnYlc%l8owl7JRvXF"},
		{"snowman dresser", "Wb5QEt&VehuZnYlOAlDosl7MRvpF"},
		{"snowman fridge", "eCO7l%UdIbWkrPkoqFQbmtfyDoyN"},
		{"snowman lamp", "gu#Pki&ug5UcBzvZd8N7wUvg#DTf"},
		{"snowman sofa", "rOimy%b6yv3&UGMZD4OOyPxdEvhu"},
		{"snowman table", "nN#PWv&wgrUcBzvrt8h7wUvg#Djf"},
		{"snowman tv", "rOHmy%b6yg3&UVMZD4OOBPxd@vhu"},
		{"snowman wardrobe", "rOimy%b6yv3&UVMZD4OOyPxdEvhu"},
		{"spooky bed", "lEskIWCWWD2OUapXV3Am@s4tRt2i"},
		{"spooky bookcase", "JTmu7yFHcMo#FYxDeynaCRxPaWge"},
		{"spooky chair", "JTmu&GJ4cEuiFYxmSynaCxeIaWge"},
		{"spooky clock", "l@skLWCWWD2ONd2fB3WmXsAe&mpi"},
		{"spooky dresser", "MA5IRydn7cG9@Q7ijb6PVncHtgCU"},
		{"spooky lamp", "JTmuEMp43fuiFYxmpynaCxePaWge"},
		{"spooky sofa", "l@sk6WOfWD2ONl2fB3TmNs4e&tpi"},
		{"spooky table", "JTmu7yFHcMo#FYxDgynaCRxIaWge"},
		{"spooky vanity", "JTmu&GJ43EuiFYxmpynaCxePaWge"},
		{"spooky wardrobe", "MAzIwydn7Yr9@Q7ijblP7ocPYgC@"},
		{"jack-in-the-box", "lEskrWOfWD2ONSpfB3km9sAt&Hpi"},
		{"jack-o'-lantern", "lEskIWCWWD2ONapfB3Am@s4t&Hpi"},
		{"backyard pool", "LKJQmrP38B%gKYUqKjaakRiVJwQa"},
		{"barbecue", "PUqIAr2#DA3r5iRBvEljRByXMZM2"},
		{"bird bath", "PUcIYr2e@Vcr5iRBvEqYjVX#MZMa"},
		{"bird feeder", "LKJQmrP38B%gKYUqKjaakR#VJwQ2"},
		{"birdhouse", "&r&DQf%&w4O4Im#x7ZD2Jh7w@PYR"},
		{"bug zapper", "PUcIAr2#@R3r5iRBvElYRBXiMZM2"},
		{"garden gnome", "PUqIYr2eDxcr5iRBvEqjjByrMZM2"},
		{"hammock", "Ir&DQ%A&s4OiIF#x7ZD2Jy&3@PqR"},
		{"lawn chair", "LKTQmrP38A%gKYUqKjaqkjTVJwQ2"},
		{"lawn mower", "#g99QNVNLqQ4exa5fXj@Hmv2dz%u"},
		{"mr. flamingo", "&r&DLf%&w4b4IF#x7ZD2Qh7w@PER"},
		{"mrs. flamingo", "PUcIYr2eDVcr5iRBvEqYjV5rMZM2"},
		{"picnic table", "Ir&DQ%A&s4OiIF#x7ZD2Jh73@PqR"},
		{"sprinkler", "fapFpuAhxvRw#AOs6oz4L@GOKTnv"},
		{"tiki torch", "IL&DL%A&sobiIF#x7Z@WMy83@#ER"},
		{"blue corner", "#g99QNVNLEQ4exa5fXj@Hmv2dz%u"},
		{"boxing barricade", "TaHFINxyxvRs#AOy6oz48@wOKTl@"},
		{"boxing mat", "TaHFIuAyxqsw#AOG6nz48DwOKTlv"},
		{"judge's bell", "#g99QNVNLEILexarfXu@HIv2Kz%u"},
		{"neutral corner", "rg99QKGNLqILtxarfXu@2Iv2Kz%u"},
		{"red corner", "TaHFpXxhxqss#AOy6nz48DwOKTl@"},
		{"ringside table", "TapFpXAhxELw#AOG6nz48DwOKTlv"},
		{"sandbag", "5Ve9QKGULqIDtxjrfXuD29v2aK&u"},
		{"speed bag", "#g99QNVNLEQLexarfXu@HIv2Kz%u"},
		{"weight bench", "#Ve9QNVULEQkexj5fXjDHmv2qz%u"},
		{"black bishop", "#g96QvVNLqQ4exh5fXV@emv2dzqu"},
		{"black king", "TaHCINAyxv4w#AtG6o44U@wOKTlv"},
		{"black knight", "#Ve6QvVULEQ%exurfXwDeIv2aKqu"},
		{"black pawn", "#g96QvVNLEILexhrfXw@eIv2Kzqu"},
		{"black queen", "faHCpXAhxEsw#Ats6n44rDGOKTnv"},
		{"black rook", "TapCpuAhxlLw#AtG6o44U@wOKTlv"},
		{"white bishop", "TaHCpuxhxv4s#Aty6o44U@wOKTl@"},
		{"white king", "TapCIuAyxqLw#AtG6n44UDwOKTlv"},
		{"white knight", "faHCpXxhxEss#Ath6n44rDGOKTn@"},
		{"white pawn", "faHCINxyxvRs#Ath6o44r@GOKTn@"},
		{"white queen", "5ge6QaVNLqQAtxh5fXV@gCv2dzlu"},
		{"white rook", "faHCpuxhxlLs#Ath6o44r@GOKTn@"},
		{"cement mixer", "LKJQmrP3UB%gKYUqKjaakR#VJwQ2"},
		{"detour arrow", "lEskrWOfWD2OUSpfB3km9sAt&epi"},
		{"detour sign", "x&3Tcr4kH2ev%udeqg2hfLDjKhjx"},
		{"flagman sign", "PUcIAr2#@R3r5iRBvElYRVXiMZMa"},
		{"green drum", "JTmu&GJ4cEuiFYxm2ynaCx#PaWge"},
		{"handcart", "l@sk6WCWWD2OUl2XV3TmNs4eRe2i"},
		{"haz-mat barrel", "Ir&DQ%A&s4OiIm#x7ZD2Jh73@PqR"},
		{"iron frame", "JTmu&GJ4cEuiFYxmpynaCxePaWge"},
		{"jackhammer", "&L&DLf%&sob4IF#x7Z@WMhow@#xR"},
		{"jersey barrier", "LKTQmrP3UA%gKYUqKjaqkRxVJwQa"},
		{"manhole cover", "JTmu&GJ4cEuiFYxm2ynaCx#IaWge"},
		{"men at work sign", "C&3Tcr4kH2ef%udelg2hfLDjKRjx"},
		{"merge sign", "x&3Tcr4kPaev%udeqg2hqoDjKhjx"},
		{"oil drum", "LKTQmrP3UA%gKYUqKjaqkjxVJwQ2"},
		{"orange cone", "lEskIWCWWD2OUapXV3Am@s4tRe2i"},
		{"saw horse", "PUqIYr2e@xcr5iRBvEqjjVyrMZM2"},
		{"speed sign", "Ir&DL%A&s4biIF#x7ZD2Qh73@PER"},
		{"steam roller", "Ir&DL%A&s4biIm#x7ZD2Qy&3@PER"},
		{"traffic cone", "JTmuEZ24cJuiFYxmgynaCRxPaWge"},
		{"wet roadway sign", "C&3Tcr4kH2ef%udeqC2hqoDRKRjx"},
		{"deer scare", "PJjThB&V#cwjZzwQ&2UyErlovId%"},
		{"garden pond", "JTmu7GJHcEo#FYxDpynaCxePaWge"},
		{"low lantern", "MHmukMI9cfo#FYx&PnnaCxeHaWge"},
		{"pond lantern", "MHmukZ79cJo#FYx&tnnaCRVpaWge"},
		{"shrine lantern", "IKyABFi#KAQtfdPp6cJQQvUMDTIN"},
		{"tall lantern", "IaBAxF4rKAQtEfDS9c%Q8vEZPY&N"},
		{"? block", "TapFpuxhxlLs#AOy6oz48@wOKTl@"},
		{"brick block", "IL&DL%A&sobiIF#x7Z@WMy83@#xR"},
		{"cannon", "fapFpuxhxv4s#AOh6oz4L@GOKTn@"},
		{"coin", "rge9QKGNLEILtxarfXu@2Iv2Kz%u"},
		{"fire flower", "#g99QNVNLqI4exa5fXj@Hmv2dz%u"},
		{"flagpole", "fapFINxyxv4s#AOh6oz4L@GOKTn@"},
		{"green pipe", "LKJQmrP3UB%gKYUqKjaakj#VJwQ2"},
		{"koopa shell", "#g99QNVNLEI4exa5fXj@Hmv2dz%u"},
		{"starman", "zge9QNVNLqQAexa5fXj@HCv2dz&u"},
		{"super mushroom", "TaHFpXxhxEss#AOy6nz48DwOKTl@"},
		{"dark stone", "JTmu7GJHcEo#FYxD2ynaCx#PaWge"},
		{"garden stone", "lEskIWCWWD2OUapfB3Am@s4t&Hpi"},
		{"leaning stone", "JTmu7GJHcEo#FYxDpynaCxeIaWge"},
		{"mossy stone", "JTmuEMp4cfuiFYxmSynaCx#PaWge"},
		{"standing stone", "JTmuEZ24cJuiFYxmeynaCRxPaWge"},
		{"stone couple", "lEskIWOfWD2OUapXV3Am@s4tRt2i"},
		{"teacher's chair", "&L&DLf%&wob4IF#x7Z@WMhow@#xR"},
		{"chalk board", "fapCpuxhxlss#Ath6o44r@GOKTn@"},
		{"cubby hole", "IaBARFi#KAQtfSDS9cQQyvUZPx7N"},
		{"flip-top desk", "IL&DL%A&wobiIm#x7Z@WMho3@#ER"},
		{"school desk", "LKJQmrP38B%gKYUqKjaakj#VJwQ2"},
		{"folding chair", "9qO4IVSfatj3FkQUjitimcCQqCft"},
		{"lefty desk", "PUqIYr2eDxcr5iRBvEqjjVyrMZMa"},
		{"righty desk", "&L&DQf%&soO4Im#x7Z@WZ2ow@#qR"},
		{"letter cubby", "IKyAAF4rKAQtfqPS9cfQDvEMPx7N"},
		{"hamster cage", "LKTQOrPgUxf9KYUqKjfqWRTRJwQ2"},
		{"mop", "zg96QvVNLEIAexh5fXV@eCv2dzlu"},
		{"science table", "MHmunGQ9cEo#FYx&PnnaCx#paWge"},
		{"teacher's desk", "PUqIAr2#@A3r5iRBvEljRVyXMZM2"},
		{"vaulting horse", "MHmukMI9cfo#FYx&7nnaCxeHaWge"},
		{"asteroid", "JTmuEZ243JuiFYxmgynaCRxPaWge"},
		{"flying saucer", "l@skLWOfWD2ONd2fB3WmXsAe&Hpi"},
		{"lunar lander", "lEskrWCWWD2ONSpfB3km9sAt&Hpi"},
		{"lunar rover", "JTmu&GJ43EuiFYxm2ynaCx#IaWge"},
		{"rocket", "JTmu3Z2HcJo#FYxDeynaCRVPaWge"},
		{"satellite", "JTmuEZ24cJuiFYxmeynaCRVPaWge"},
		{"space shuttle", "l@skLWOfWD2ONd2XV3WmXsAeRC2i"},
		{"space station", "JTmu&GJ43EuiFYxmpynaCx#PaWge"},
		{"spaceman sam", "lEskIWOfWD2OUapfB3Am@s4t&Fpi"},
		{"covered wagon", "&r&DQf%&s4O4Im#x7ZD2Jy&w@PqR"},
		{"cow skull", "&L&DQf%&soO4Im#x7Z@WZn8w@#YR"},
		{"desert cactus", "zV99QNVULEQDexjrfXuDH9v2aK&u"},
		{"saddle fence", "LKJQOrPg8Rf9KYUqKjfaWR#RJwQ2"},
		{"storefront", "PUqIAr2#DA3r5iRBvEljRVyXMZMa"},
		{"tumbleweed", "PUqIAr2#DA3r5iRBvEljRBhiMZMa"},
		{"wagon wheel", "zVe9QNVULEQmexj5fXjDHCv2qz&u"},
		{"watering trough", "PUqIYr2eDxcr5iRBvEqjjVh#MZM2"},
		{"well", "fapFpXxhxEss#AOh6nz4LDGOKTn@"},
		{"western fence", "LKJQOrPg8Rf9KYUqKjfaWRiRJwQa"},
		{"apple clock", "#g96QvVNLEQ4exh5fXV@emv2dzqu"},
		{"apple tv", "MHmunGQ9cEo#FYx&InnaCxeHaWge"},
		{"baby bear", "MAzIRydn7Yr9@Q7ijbdP7ncPYgC@"},
		{"mama bear", "MA5Iwydn7cG9@Q7ijb6PVncHtgCU"},
		{"papa bear", "@PYIwZdBRcw9@Q2NY5yPVncHtgTU"},
		{"mugho bonsai", "hysFmijgbKGjqxG%RuWkV5j@rQpk"},
		{"pine bonsai", "PJjThB&V#bwjZzwQ&2U6ErlovId%"},
		{"ponderosa bonsai", "2yoF3GVgFri&%xGkwo2OXrJvqBpc"},
		{"cactus", "l7RuzQ2WhgsL&jBAmn8tQ5INFDDp"},
		{"round cactus", "IKyAAF4rKAQtEqPp6cfQDvEMDTIN"},
		{"tall cactus", "MHmukZ79cJo#FYx&tnnaCRxHaWge"},
		{"grapefruit table", "2hsF3GjWFMH&%xGk3o2OirJvqApc"},
		{"lemon table", "IaBARF4rKAQtESDS9cQQyvUZPA7N"},
		{"lime chair", "d7RuzQgghesL&jBAkn8zZ5QNFDDp"},
		{"orange chair", "MHmunGQ9cEo#FYx&7nnaCx#HaWge"},
		{"daffodil table", "MHmulGQ5cEuiFYx7InnaCx#HaWge"},
		{"daffodil chair", "IKyAAF4rKAQtfqPS9cfQDvEMPT7N"},
		{"iris chair", "MHmukMI9cfo#FYx&InnaCxeHaWge"},
		{"iris table", "IKyAAF4rKAQtEqPS9cfQDvEMPx7N"},
		{"tulip chair", "MHmulGQ5cEuiFYx7DnnaCx#HaWge"},
		{"tulip table", "IKyABF4rKAQtfdPS9cJQQvUMPT7N"},
		{"conga drum", "hOu6jhEN6UFO8Dcy@jvDbHnuz8xY"},
		{"djimbe drum", "2hsF3hVgFrH&%xGkwo2nirJvqApc"},
		{"timpano drum", "hOu6R2EN6UFO8D5yetVPiD7ujoxY"},
		{"aiko figurine", "TaHCINxyxvRs#Aty6o44U@wOKTl@"},
		{"emi figurine", "hOu6jpEi6UFY8DyGeBVUbPOuz8xY"},
		{"keiko figurine", "hOu6jpEi6UFe8D5GeBVUbPOuz8xY"},
		{"maki figurine", "rWM4L#tfEjS&HkfwwAdCYuEljpft"},
		{"naomi figurine", "rFM46PeWfjpaHkq#w%dCBuEdRFfP"},
		{"yoko figurine", "9qO4LxDTvtj3FkZxjitimcCQECfP"},
		{"yuki figurine", "hOu6jhEN6UFO8Dby@jvDuS7ujoxY"},
		{"froggy chair", "CtZMuf7pazEqFLJAvmbUHdX9&pC8"}, // from Hunter Irving :)
		{"lily-pad table", "@PYIwZdBRYwv@Q28Y5lP7nqHxgTU"},
		{"folk guitar", "MAzIwydn7cr9@Q7ijbyPRocPtgC@"},
		{"country guitar", "@PYIwZdBRYw9@Q2NY5dP7ncHYgTU"},
		{"rock guitar", "@PYIRZdBRcwv@Q28Y56PVnqpegTU"},
		{"luigi trophy", "LKJQmrP3UB%gKYUqKjaakRiVJwQ2"},
		{"mario trophy", "IL&DL%A&sobiIF#x7Z@WMho3@#ER"},
		{"melon chair", "l@sk6WOfWD2ONl2XV3TmNs4eRe2i"},
		{"watermelon chair", "l@skLWOfWD2OUd2XV3WmXsAeRt2i"},
		{"watermelon table", "JTmu&GJ4cEuiFYxmpynaCx#PaWge"},
		{"arwing", "lEskIWOfWD2ONapXV3Am@s4tRC2i"},
		{"g logo", "x&3Tcr4kH2ev%udelg2hfLDRKhjx"},
		{"master sword", "9dO4LxDTvtjcFkZxjNtiwcCLECfP"},
		{"n logo", "hOu6RFEi6UFY8DbG@Hv#zHOuz8xY"},
		{"office chair", "MHmu%MI5cfuiFYx7PnnaCx#HaWge"},
		{"office desk", "9dO4LxDTvtjcFkZUjNtiwcCLECfP"},
		{"office locker", "MAzIwydn7cr9@Q7ijb6PVocItgC@"},
		{"pear dresser", "MA5IRydn7cG9@Q7ijbyPRocHtgCU"},
		{"pear wardrobe", "@PYIwZdBRcw9@Q2NY56PVncptgTU"},
		{"pine chair", "MHmu%Z75cJuiFYx7tnnaCRxpaWge"},
		{"pine table", "IKyABFi#KAQtEdPS9cJQQvUMPT7N"},
		{"robo-clock", "TaHCIuAyxqsw#AtG6n44UDwOKTlv"},
		{"robo-stereo", "rg96QaVNLqILtxhrfXw@gIv2Kzqu"},
		{"bass", "JTmu3MpHcfo#FYxDpynaCxePaWge"},
		{"cello", "JTmu3MpHcfo#FYxDHynaCxeIaWge"},
		{"violin", "l@skLWOfWD2ONd2XV3WmXsAeRe2i"},
		{"bear pole", "hOu6jpEi6UFx8DbG@jvUbHOuz8xY"},
		{"eagle pole", "hOu6R2EN6UF38DyyetVPzPnuz8xY"},
		{"frog woman pole", "hOu6RFEi6UFt8D5GetV#iDmujoxY"},
		{"raven pole", "hOu6RFEi6UFY8D5GetV#iDmujoxY"},
		{"blue vase", "MHmulGQ5cEuiFYx7InnaCxepaWge"},
		{"red vase", "IKyAAF4rKAQtEqPp6cfQDvEMDY7N"},
		{"tea vase", "IaBARFi#KAQtfSDp6cQQyvUZDY7N"},
		{"candy machine", "IL&DQ%A&soOiIm#x7Z@WZn83@#qR"},
		{"coffee machine", "LKTQOrPgUxf9KYUqKjfqWRxRJwQ2"},
		{"pop machine", "lEskIWOfWD2OUapXV3Am@s4tRe2i"},
		{"soda machine", "lEskIWOfWD2ONapXV3Am@s4tRe2i"},
		{"globe", "hOu6RFEi6UFt8DyGetV#zPOuz8xY"},
		{"writing chair", "9qO4LxDTvt23FkZxjitimcCQECfP"},
		{"writing desk", "hOu6RFEi6UFe8DbG@Hv#iSmujoxY"},
		{"barber's pole", "lnRuzQgghCQL&jBAkn8BA5INFUDp"},
		{"birdcage", "hOu6RFEi6UFx8DbG@Hv#zHOuz8xY"},
		{"bus stop", "&r&DLf%&s4b4Im#x7ZD2Qh7w@PER"},
		{"extinguisher", "hOu6R2EN6UF38Dcy@HvPiS7ujoxY"},
		{"fan", "@AZIwZdB7cw9@Q2NY5yPVncptgTU"},
		{"garbage can", "JTmu&GJ4cEuiFYxmpynaCxeIaWge"},
		{"trash bin", "JTmu&GJ4cEuiFYxmSynaCx#PaWge"},
		{"tea set", "lEskIWCWWD2ONapfB3Am@s4t&Fpi"},
		{"glass-top table", "MHmunym9cMo#FYx&tnnaCRVHaWge"},
		{"orange box", "zg99QNVNLEIQexhrfXw@H9v2Kz&u"},
		{"pineapple bed", "MHmunGQ9cEo#FYx&InnaCxepaWge"},
		{"potbelly stove", "PUcIYr2e@Vcr5iRBvEqYjBX#MZMa"},
		{"radiator", "PUcIYr2e@Vcr5iRBvEqYjV5rMZMa"},
		{"rocking chair", "9qO4LxSfat23FkQ#jitimcCQECfP"},
		{"scale", "l@skLWCWWD2ONd2fB3WmXsAe&Fpi"},
		{"sewing machine", "IaBAxF4rKAQtEfDp6c%Q8vEZDTIN"},
		{"space heater", "hOu6jpEi6UFe8DbG@jvUbHOuz8xY"},
		{"refrigerator", "MAzIRydn7cr9@Q7ijb6PVocItgC@"},
		{"stove", "MAzIwydn7Yr9@Q7ijbdP7ncPYgC@"},
		{"mochi pestle", "JTmu3Z2H3Jo#FYxD@ynaCRVIaWge"},
		{"biwa lute", "rFM4L#eWfjpaHkq#w%dCBuEdjpft"},
		{"taiko drum", "hOu6jhEN6UFc8Dby@jvDbHnuz8xY"},
		{"chess table", "LKTQmrP38A%gKYUqKjaqkRxVJwQ2"},
		{"table tennis", "MHmukZ79cJo#FYx&tnnaCRVHaWge"},
		{"billiard table", "IaBARFi#KAQtESDp6cQQyvUZDY7N"},
		{"executive toy", "l@skLWOfWD2OUd2fB3WmXsAe&epi"},
		{"slot machine", "HJjTha7e#bwhZzwQ&2U6ErlovId%"},
		{"water bird", "l7RuzMgghgsL&jBAkn8BQ5INFDDp"},
		{"wobbelina", "2yoF3GjWFri&%xGk3o2nXrJvqBpc"},
		{"computer", "hOu6jpEi6UFt8DyGeBVUbPOuz8xY"},
		{"toilet", "MHmulym5cMuiFYx7dnnaCRxHaWge"},
		{"super toilet", "MHmunGQ9cEo#FYx&DnnaCx#paWge"},
		{"daffodil", "JTmuEZ243JuiFYxmeynaCRxPaWge"},
		{"gerbera", "lEskrWOfWD2OUSpfB3km9sAt&Cpi"},
		{"sunflower", "lEskIWCWWD2OUapfB3Am@s4t&Fpi"},
		{"hinaningyo", "@PYIRZdBRcw9@Q2NY56PRncptgTU"},
		{"samurai suit", "fapCpuxhxlLs#Ath6o44r@GOKTn@"},
		{"tanabata palm", "5Ve9QKGULqIDtxurfXwD29v2aK&u"},
		{"elephant slide", "MHmukMI9cfo#FYx&PnnaCxepaWge"},
		{"train set", "lnRuzQgghCQL&jBAkn8tA5INFUDp"},
		{"retro tv", "rFM46PtfEjpaHkf3w%dCBuEdRFfP"},
		{"wide-screen tv", "MHmunGQ9cEo#FYx&DnnaCx#HaWge"},
		{"big festive tree", "zV96QvVULEQmexu5fXVDeCv2qzlu"},
		{"festive tree", "zg96QvVNLqQQexhrfXw@e9v2Kzlu"},
		{"festive candle", "LKTQmrP3UA%gKYUqKjaqkRTVJwQa"},
		{"festive flag", "Ir&DL%A&s4biIm#x7ZD2Qh73@PER"},
		{"metronome", "TJjTha7e#KwhZzwQ&2N5frdovId%"},
		{"harp", "d7RuzQ2WhVsL&jBAmn8zZ5QNFDDp"},
		{"vibraphone", "9dO4IVSfat2cFkQUjNtiwcCLqCft"},
		{"ebony piano", "JTmu&yF4cMuiFYxm@ynaCRxPaWge"},
		{"ivory piano", "hOu6R2EN6UFC8DyyetVPiD7ujoxY"},
		{"barrel", "MHmukZ79cJo#FYx&dnnaCRVpaWge"},
		{"keg", "MHmulGQ5cEuiFYx7InnaCxeHaWge"},
		{"blue golf bag", "hOu6jhEN6UFC8Dcy@jvDuS7ujoxY"},
		{"green golf bag", "9qO4LxSfatj3FkQ#jitimcCQECfP"},
		{"white golf bag", "rFM46PeWfjpaHkqUw%dCBuEdRFfP"},
		{"nook's portrait", "l@skLWOfWD2OUd2fB3WmXsAe&Fpi"},
		{"cream sofa", "MA5IRydn7cG9@Q7ijbyPRncptgCU"},
		{"red sofa", "MA5Iwydn7cG9@Q7ijb6PVncptgCU"},
		{"red armchair", "MA5IRydn7YG9@Q7ijbdP7ncHYgCU"},
		{"gold econo-chair", "rWM4L#tfEjp&HkfwwAdCYuEljpft"},
		{"jade econo-chair", "rFM46PeWfjSaHkqxw%dCBuEdRFfP"},
		{"ruby econo-chair", "hOu6jpEi6UFY8DcG@jvUbHOuz8xY"},
		{"alarm clock", "IKyAAF4rKAQtEqPS9cfQDvEMPA7N"},
		{"antique clock", "#g96QvVNLEQLexhrfXw@eIv2Kzqu"},
		{"cube clock", "faHCpXxhxqss#Ath6n44rDGOKTn@"},
		{"glow clock", "TapCINxyxlss#Aty6o44U@wOKTl@"},
		{"kitschy clock", "TapCpXAhxELw#AtG6n44UDwOKTlv"},
		{"odd clock", "zVe6QvVULEIDexurfXwDe9v2aKlu"},
		{"owl clock", "fapCIuxyxELs#Ath6n44rDGOKTn@"},
		{"red clock", "fapCpuAhxvRw#Ats6o44r@GOKTnv"},
		{"azalea bonsai", "JTmuEMp4cfuiFYxmpynaCxePaWge"},
		{"hawthorn bonsai", "JTmu3MpHcfo#FYxDHynaCxePaWge"},
		{"holly bonsai", "lEskrWOfWD2OUSpXV3km9sAtRH2i"},
		{"jasmine bonsai", "JTmu3Z2HcJo#FYxDeynaCRxPaWge"},
		{"maple bonsai", "l@skLWCWWD2ONd2fB3WmXsAe&Hpi"},
		{"quince bonsai", "l@skLWCWWD2ONd2fB3WmXsAe&Ppi"},
		{"plum bonsai", "phRFmzhgbYGjqxG%Rucdh5HDrQpk"},
		{"aloe", "2yoF3GjWFri&%xGk3o2OXrJvqBpc"},
		{"bromeliaceae", "d7RuzQ2WhesL&jBAmn8YZ5QNFDDp"},
		{"caladium", "d7RuzM2WhesL&jBAmn8zZ5QNFDDp"},
		{"coconut palm", "pysFmijgbYGjqxG%Rucdj5H@rQpk"},
		{"corn plant", "HJjTha7e#bwhZzwQ&2UyErlovId%"},
		{"croton", "l7RuzQgghgsL&jBAkn8BQ5INFDDp"},
		{"dracaena", "bnoF3GVgFEi&%xGkwo2o5wpvqBpc"},
		{"fan palm", "2hsF3GVgFrH&%xGkwo2OirJvqApc"},
		{"lady palm", "hhRFmzhgbqGjqxG%RuWkG5jDrQpk"},
		{"pachira", "AMjThj7V#qwjZzwQ&2N5TrdbvId%"},
		{"pothos", "lnRuzMgghCQL&jBAkn8BA5INFUDp"},
		{"rubber tree", "AMjThB&V#qwjZzwQ&2NZTrdbvId%"},
		{"snake plant", "bnoF3hVgFEi&%xGkwo2k5wpvqBpc"},
		{"weeping fig", "b2sF3hjWFUH&%xGk3o2ozwpvqApc"},
		{"tape deck", "#Ve6QvVULEQkexu5fXVDemv2qzqu"},
		{"red boom box", "fapCINxyxv4s#Ath6o44r@GOKTn@"},
		{"white boom box", "5g96QaVNLEQQtxhrfXw@g9v2Kzlu"},
		{"cd player", "5g96QaVNLEIQtxhrfXw@g9v2Kzlu"},
		{"phonograph", "hSAfTSfoTHhR8MndeMwsn2imjduq"},
		{"jukebox", "rge6QaVNLqQ4txh5fXV@gmv2dzqu"},
		{"turntable", "hSAffpfoTHhR8MndeG3&O2imjdW5"},
		{"retro stereo", "9qO4IVDTvt23FkZEjitimcCQqCft"},
		{"high-end stereo", "TaHCpXxhxEss#Aty6n44UDwOKTl@"},
		{"reel-to-reel", "5Ve6QaVULqIDtxurfXwDg9v2aKlu"},
		{"gold stereo", "hOu6jhEN6UFC8DyyeBVDuD7ujoxY"},
		{"lovely stereo", "rge6QaVNLEILtxhrfXw@gIv2Kzqu"},
		{"dice stereo", "TaHCpXxhxqss#Aty6n44UDwOKTl@"},
		{"hi-fi stereo", "fapCIuAyxqLw#Ats6n44rDGOKTnv"},
		{"classic painting", "MHmunym9cMo#FYx&nnnaCRxpaWge"},
		{"fine painting", "MHmu%Z75cJuiFYx7tnnaCRVHaWge"},
		{"perfect painting", "IaBAxFi#KAQtffDp6c%Q8vEZDY7N"},
		{"rare painting", "IKyABF4rKAQtfdPp6cJQQvUMDAIN"},
		{"strange painting", "MHmunym9cMo#FYx&tnnaCRxHaWge"},
		{"worthy painting", "MHmu%MI5cfuiFYx7DnnaCx#HaWge"},
		{"amazing painting", "MHmunGQ9cEo#FYx&PnnaCxeHaWge"},
		{"basic painting", "MHmukZ79cJo#FYx&dnnaCRVHaWge"},
		{"common painting", "IaBARFi#KAQtESDS9cQQyvUZPA7N"},
		{"dainty painting", "MHmulGQ5cEuiFYx7DnnaCxepaWge"},
		{"famous painting", "MHmu%Z75cJuiFYx7tnnaCRxHaWge"},
		{"flowery painting", "IaBAxFi#KAQtffDS9c%Q8vEZPA7N"},
		{"moving painting", "MHmukMI9cfo#FYx&7nnaCx#HaWge"},
		{"quaint painting", "IaBAxF4rKAQtffDp6c%Q8vEZDY7N"},
		{"scary painting", "IKyABFi#KAQtfdPS9cJQQvUMPx7N"},
		{"chowder", "#Ve9QNVULqQkexj5fXjDHmv2qz%u"},
		{"crab stew", "C&3Tcr4kPaef%udelC2hfLDjKjjx"},
		{"fireplace", "RhGRWk&TSaNKcMi%BAP3lHSzfzXf"},
		{"sleigh", "RaGRWk&TSaNKcMi%oxP7%HSbfzuf"},
		{"snow bunny", "RaGRWkaTSaNKcMi%BAP7%HSbfzWf"},
		{"snowboard", "x&3Tcr4kPaev%udelC2hqoDjKhjx"},
		{"backpack", "fapFIuxyxELs#AOh6nz4LDGOKTn@"},
		{"bonfire", "TapFINxyxlss#AOy6oz48@wOKTl@"},
		{"campfire", "5g99QKGNLEIQtxarfXu@29v2Kz&u"},
		{"cooler", "TapFIuAyxqLw#AOG6nz48DwOKTlv"},
		{"kayak", "zVe9QNVULEIDexjrfXuDH9v2aK&u"},
		{"lantern", "TaHFpuxhxv4s#AOy6oz48@wOKTl@"},
		{"mountain bike", "TaHFINAyxv4w#AOG6oz48@wOKTlv"},
		{"propane stove", "#Ve9QNVULEQ%exjrfXuDHIv2aK%u"},
		{"sleeping bag", "faHFpXxhxEss#AOh6nz4LDGOKTn@"},
		{"beach chair", "RaGRWkaTSaNKcMi%oxP7lHSbfzWf"},
		{"beach table", "x&3Tcr4kPaev%udeqg2hqoDjKsjx"},
		{"diver dan", "C&3Tcr4kH2ef%udelg2hqoDjKjjx"},
		{"life ring", "fapFpXAhxqsw#Ats6ni8LDGOKTnv"},
		{"snowcone machine", "RaGRWk&TSaNKcMi%oAP7%HSbfzuf"},
		{"surfboard", "C&3Tcr4kH2ef%udeqC2hfLDRKRjx"},
		{"treasure chest", "RaGRWk&TSaNKcMi%BAP7lHSbfzuf"},
		{"ukulele", "x&3Tcr4kH2ev%udelg2hfLDjKhjx"},
		{"wave breaker", "RhGRWkaTSaNKcMi%BxP3%HSzfzhf"},
		{"arc de triomphe", "rge9QKGNLEILtxhrfXw@2Iv2Kz%u"},
		{"chinese lion", "#g99QNVNLEQLexhrfXw@HIv2Kz%u"},
		{"chinese lioness", "rOHmy%b6LW3&UGMZUoObBPxdEvhu"},
		{"compass", "zVe9QNVULEIDexurfXwDH9v2aK&u"},
		{"fishing bear", "rOHmy%b6LW3&UVMZDoOKnPxd@vho"},
		{"lady liberty", "fapFIuAyxqLw#Ats6ni8LDGOKTnv"},
		{"manekin pis", "gu#PWN&wg5UcBzv5d8N7w&vg#DTf"},
		{"matryoshka", "nN#Pki&ug5UcBzvZt8Nww&vg#Djf"},
		{"merlion", "kb5QEY&VesNZnYlC%lQksl7MRvXF"},
		{"mermaid statue", "zge9QNVNLqQAexh5fXV@HCv2dz&u"},
		{"moai statue", "Wb5Qfd&RxJuZnYlcAl8owl7JRvpF"},
		{"mouth of truth", "kb5Qfq&RxQNZnYl3%lskw87JRvXF"},
		{"pagoda", "gu#P3i&uu6UcBzvZd8S7sUv7#DTf"},
		{"plate armor", "fapFpXxhxEss#Ath6ni8LDGOKTn@"},
		{"shogi piece", "eCb7l%UdQSXkrIkolHQdQtfy%oy8"},
		{"stone coin", "TapFpuxhxlLs#Aty6oi88@wOKTl@"},
		{"tiger bobblehead", "eCO7l%UdQFXkrIkoqHQOmtfy%oyN"},
		{"tokyo tower", "Wb5Q%Y&VxQNZnYlCAlskwl7JRvpF"},
		{"tower of pisa", "kb5Q%Y&VxQNZnYlC%lsow87JRvXF"},
		{"tribal mask", "rOHmy%b6yg3&UGMZD4OdnPxd@vho"},
		{"nintendo bench", "RhGRWk&TSaNKcMi%oxP7lHSzfzhf"},
		{"birthday cake", "rFM46PeWfjpaHkqxw%dCBuEdRFfP"},
		{"chocolates", "rOimy%b6Lf3&UVMZUoOKlPxdEvho"},
		{"tissue", "gu#PkV&ugrUcBzvMd8hwwUvg#DTf"},
		{"piggy bank", "kb5QEY&VesNZnYlC%lQos87MRvXF"},
		{"mailbox", "IL&DQ%A&woOiIm#x7Z@WZn83@#YR"},
		{"telescope", "&L&DQf%&soO4IF#x7Z@WZn8w@#YR"},
		{"aerobics radio", "gu#Pki&ug5UcBzvZd8N7w&vg#DTf"},
		{"angler trophy", "fapFpXAhxqsw#AOs6nz4LDGOKTnv"},
		{"autumn medal", "PUcIAr2#@R3r5iRBvElYRBXiMZMa"},
		{"spring medal", "Ir&DQ%A&w4OiIF#x7ZD2Jy&3@PqR"},
		{"bottle rocket", "RhGRWk&TSaNKcMi%BAP7lHSzfzXf"},
		{"bottled ship", "eCb7l%UdQSXkrIkolHQODtfyDoyN"},
		{"cornucopia", "faHFINxyxvRs#AOh6oz4L@GOKTn@"},
		{"dolly", "TapFIuAyxqLw#AtG6ni88DwOKTlv"},
		{"fishing trophy", "PUcIYr2eDVcr5iRBvEqYjB5rMZM2"},
		{"lovely phone", "#g99QNVNLEQ4exh5fXV@Hmv2dz%u"},
		{"moon", "TaHFpuxhxv4s#Aty6oi88@wOKTl@"},
		{"noisemaker", "zg99QNVNLqQQexarfXu@H9v2Kz&u"},
		{"balloon fight", "hSAffp%4THhj8Mndi9r&Cjimb63c"},
		{"baseball", "hSAfTSfzTtuzNMnde9G&Cjimb63t"},
		{"clu clu land", "hSAfTpfoTHhRNMndeG3sO2imjdu5"},
		{"dk jr math", "hSkfTp%oTHhR8MndeG3&O2imzt3Z"},
		{"donkey kong", "hSAffp%4THhjNMndi9rsCjimb63c"},
		{"excitebike", "hSAffSfoTHhRNMndeMwsn2imjdWq"},
		{"golf", "hSAfTp%4THhjNMndi9rsCjimb63c"},
		{"pinball", "hSAfTS%4THhzNMndi9G&Cjim2twY"},
		{"tennis", "hSAffSfoTHhR8MndeMw&n2imjduq"},
		{"wario's woods", "hSAffpfoTHhR8MndeG3&O2imztW5"},
		{"nes", "hSAfTpfoTHhRNMndeG3&O2imjdW5"},
		{"super tortimer", "PUcIYr2e@Vcr5iRBvEqYjBX#MZM2"},
		{"cosmos model 1", "zg99QNVNLEQQexarfXu@H9v2Kz&u"},
		{"cosmos model 2", "zV99QNVULEQmexj5fXjDHCv2qz&u"},
		{"cosmos model 3", "faHFpuxhxlLs#AOh6oz4L@GOKTn@"},
		{"pansy model 1", "5g99QKGNLEIAtxa5fXj@2Cv2dz&u"},
		{"pansy model 2", "fapFpuxhxlLs#AOh6oz4L@GOKTn@"},
		{"pansy model 3", "fapFpXxhxqss#AOh6nz4LDGOKTn@"},
		{"tulip model 1", "TapFpuAhxlLw#AOG6oz48@wOKTlv"},
		{"tulip model 2", "5ge9QKGNLqQAtxa5fXj@2Cv2dz&u"},
		{"tulip model 3", "faHFpXAhxEsw#AOs6nz4LDGOKTnv"},
		{"dirt model", "#V99QNVULqQ%exurfXwDHIv2aK%u"},
		{"grass model", "zg99QNVNLEIAexh5fXV@HCv2dz&u"},
		{"weed model", "fapFpXxhxqss#Ath6ni8LDGOKTn@"},
		{"pink tree model", "fapFpuxhxlLs#Ath6oi8L@GOKTn@"},
		{"tree model", "5g99QKGNLEIAtxh5fXV@2Cv2dz&u"},
		{"snowy tree model", "C&3Tcr4kPaef%udelC2hfLDRKjjx"},
		{"igloo model", "x&3Tcr4kH2ev%udelC2hqoDRKhjx"},
		{"snowman", "TapFpuAhxlLw#AtG6oi88@wOKTlv"},
		{"tent model", "faHFpXxhxqss#AOh6nz4LDGOKTn@"},
		{"track model", "rg99QKGNLEQLtxhrfXw@2Iv2Kz%u"},
		{"locomotive model", "#g99QNVNLqQ4exh5fXV@Hmv2dz%u"},
		{"train car model", "TaHFpuAhxvRw#AtG6oi88@wOKTlv"},
		{"miniature car", "5ge9QKGNLqQAtxh5fXV@2Cv2dz&u"},
		{"dump model", "zV99QNVULEQmexu5fXVDHCv2qz&u"},
		{"well model", "fapFpuxhxlss#Ath6oi8L@GOKTn@"},
		{"katrina's tent", "TapFpXAhxELw#AtG6ni88DwOKTlv"},
		{"market model", "TaHFIuAyxqsw#AtG6ni88DwOKTlv"},
		{"police model", "#g99QNVNLqI4exh5fXV@Hmv2dz%u"},
		{"shop model", "TapFINxyxlss#Aty6oi88@wOKTl@"},
		{"post model", "#g99QNVNLEI4exh5fXV@Hmv2dz%u"},
		{"tailor model", "zg99QNVNLEQQexhrfXw@H9v2Kz&u"},
		{"lighthouse model", "fapFIuxyxELs#Ath6ni8LDGOKTn@"},
		{"house model", "fapFpuxhxv4s#Ath6oi8L@GOKTn@"},
		{"manor model", "zV99QNVULEQDexurfXwDH9v2aK&u"},
		{"museum model", "zVe9QNVULEQmexu5fXVDHCv2qz&u"},
		{"station model 1", "TaHFINAyxv4w#AtG6oi88@wOKTlv"},
		{"station model 2", "faHFpXxhxEss#Ath6ni8LDGOKTn@"},
		{"station model 3", "#Ve9QNVULEQ%exurfXwDHIv2aK%u"},
		{"station model 4", "faHFINxyxvRs#Ath6oi8L@GOKTn@"},
		{"station model 5", "#g99QNVNLEILexhrfXw@HIv2Kz%u"},
		{"station model 6", "zg99QNVNLqQQexhrfXw@H9v2Kz&u"},
		{"station model 7", "#Ve9QNVULqQkexu5fXVDHmv2qz%u"},
		{"station model 8", "rV99QKGULqQ%txurfXwD2Iv2aK%u"},
		{"station model 9", "rV99QKGULEIktxu5fXVD2mv2qz%u"},
		{"station model 10", "zV99QNVULEIDexurfXwDH9v2aK&u"},
		{"station model 11", "TaHFpXxhxELs#Aty6ni88DwOKTl@"},
		{"station model 12", "faHFIuxyxqLs#Ath6ni8LDGOKTn@"},
		{"station model 13", "rge9QKGNLEQ4txh5fXV@2mv2dz%u"},
		{"station model 14", "TapFpuxhxv4s#Aty6oi88@wOKTl@"},
		{"station model 15", "5Ve9QKGULEQDtxurfXwD29v2aK&u"},
		{"blue diary", "gVWYt3geqY#AOjFn8TXvFxyjIHHZ"},
		{"blue polka pad", "kVEzxmU@BBzIoFFPtCQG2enykUrP"},
		{"calligraphy pad", "gV2YHMgHOYzQORSnUTXvWxGaIHHZ"},
		{"captain's log", "3VWYHMnpxYzZmRHn8YkvbZuaLFTZ"},
		{"college rule", "kVEzTmKHGjU6bFSP6CsG392Vm@MP"},
		{"diary", "yVvzYD#MYXG%zWFkPmou79Ga5Z6%"},
		{"french notebook", "yVEzAmzFMiyY4kHkDmou3IhvZyy%"},
		{"green plaid pad", "3BfYHMn6CYbZOsHn8Tpvbsh&LtQO"},
		{"journal", "kVEzAmKevjG6omSPtCQGkX2VD9yP"},
		{"organizer", "3VWYHMnpxYzZmRHn8YkvbZuaLHTZ"},
		{"pink diary", "3BTYt376rjGYmhFn8Ykvbhh&LOQO"},
		{"pink plaid pad", "kVvzxmKegyz6oFSPtCQGcp7Bm@GP"},
		{"red polka pad", "2R7q#mze&5VjP7Mn5PxGliLro8hQ"},
		{"school pad", "7h&ZiInPPilhPsMB5e45@esLomQO"},
		{"scroll", "cVWctE49EtwYO7SB#TMSwTXvLKJQ"},
		{"yellow plaid pad", "7s7Zzm2@sHGjtjMB5Pi5@4sXoOJZ"},

		// Wallpaper
		{"chic wall", "pOuQRFEi9wFP8DcG@HvxzHOuz8xc"},
		{"classic wall", "pOiQR2@N9#JW8DuBetVRiS7ujoxc"},
		{"parlor wall", "poiQjS@i6UJY8DbGeBVUuSmGjoxY"},
		{"stone wall", "9ZBiXEas&9&3FkQCjiti%cCAwCf4"},
		{"blue-trim wall", "rFMiL#tfERHaHkfww%dCBuEdapft"},
		{"plaster wall", "pOuQjseN9#Jm8DuBeBBRuS7ujoVc"},
		{"classroom wall", "rW@i6#VFfR7&HbqUwxdCYuvn&Fft"},
		{"lovely wall", "p4uQjSvi6riY8m5GPBRUb#OGTmxY"},
		{"exotic wall", "9qOiLxSfae23FkQ#jitimcCQ3CfP"},
		{"mortar wall", "9dOiLVDive2cFbZEjK6iwcwL3CNt"},
		{"gold screen wall", "pouQRPei6UJY8DbGetBrzHOGz8VY"},
		{"tea room wall", "p4uQRHEi6rie8myGPtR#z#mGHmxY"},
		{"citrus wall", "pOuQjhEN9wFm8D5yeBV&bPnuz8xc"},
		{"cabin wall", "9dOiLVSNaejcFbQUjK6iwcwL3CNt"},
		{"blue tarp", "rW@i6PBfERP&HbfE#xdCYuEnapfP"},
		{"lunar horizon", "p4uQjSvi6rie8mcGDj&UbzdGTmxY"},
		{"garden wall", "pOuQRFEi9wFH8DbG@HvxiSmujoxc"},
		{"spooky wall", "rFMi6#tNERHaHbfUwEdCBuvd&FNt"},
		{"western vista", "rW@i6PVWfRP&Hbqx#xdCYuEnapfP"},
		{"green wall", "p4uQRjvN6ric8mbyDH&PzzlGTmxY"},
		{"blue wall", "pOuQjpEi9wFH8D5GeBVEbPOuz8xc"},
		{"regal wall", "pOuQjIei9#JP8DWVeBBxbHOuz8Vc"},
		{"ranch wall", "pouQRReN6UJ38DcyetBIzHnGz8VY"},
		{"modern wall", "96BiXEas&9IcFkQMjNti&cC4wCf4"},
		{"cabana wall", "pOuQjhEN9wFm8Dby@jv&uS7ujoxc"},
		{"snowman wall", "pOuQjIei9#JP8DWVeBBxuSmujoVc"},
		{"backyard fence", "rF@i6PBfER7aHbfU#EdCBuEOapfP"},
		{"music room wall", "96Bipv&wl9&cFkZ3jNti&cC4bCfz"},
		{"plaza wall", "9qOiLxDTvej3FkZxjitimcCQ3CfP"},
		{"lattice wall", "9dOiLxSvae2cFbQxbz6iwcCLcCNP"},
		{"ornate wall", "poiQja@N6UJ38DcyeBVDbHnGz8xY"},
		{"modern screen", "p4uQRHEi6rix8myGPtR#z#mGHmxY"},
		{"bamboo wall", "pOuQjpEi9wFA8DyGeBVEbPOuz8xc"},
		{"kitchen wall", "9dOiLxSvaejcFbQUbz6iwcCLcCNP"},
		{"old brick wall", "9dtiLV&Hve7cFbZxjK6iwcw43Cft"},
		{"stately wall", "rTvi9DVV%sI&HkYrwAdCzuEnUFf4"},
		{"imperial wall", "rWMiL#tfERH&HkfwwAdCYuElapft"},
		{"manor wall", "rFMi6#eufRHaHbqUwEdCBuvd&FNt"},
		{"ivy wall", "poiQjS@i6UJt8DbGeBVUuSmGjoxY"},
		{"mod wall", "p4uQRjEN6riO8myyPtRPz#7GHmxY"},
		{"rose wall", "rFMi6PeWfR2aHkq#w%dCBuEd&FfP"},
		{"wood paneling", "pOiQjh@N9#JF8DuBeBV&bHnuz8xc"},
		{"concrete wall", "pouQRReN6UJc8DbyetBIzHnGz8VY"},
		{"office wall", "p4uQRHEi6rix8m5GPtR#z#mGHmxY"},
		{"ancient wall", "pOuQRFEi9wFP8DyGetVxzPOuz8xc"},
		{"exquisite wall", "pOuQjIei9#JT8DWVeBBxbHOuz8Vc"},
		{"sandlot wall", "9qtiLV&Hve73FbZ#jz6imcwA3Cft"},
		{"jingle wall", "p4uQjSvi6riY8mcGDj&UbzdGTmxY"},
		{"meadow vista", "rFMi6PeWfR2aHkqEw%dCBuEd&FfP"},
		{"tree-lined wall", "rFMi6PegfRHaHbq##EdCBuEdapNP"},
		{"mosaic wall", "poiQRj@N6UJc8DcyetVPiS7GjoxY"},
		{"arched window", "p4uQjavN6ri38m5yPBRDb#nGTmxY"},
		{"basement wall", "pOuQjhEN9wFF8DyyeBV&bPnuz8xc"},
		{"backgammon wall", "9dOiLVDivejcFbZxjK6iwcwL3CNt"},
		{"kiddie wall", "poiQja@N6UJc8DcyeBVDuS7GjoxY"},
		{"shanty wall", "9ZBiXE&wl9&3FkZMjiti%cCAwCf4"},
		{"industrial wall", "rFMi6PtfER2aHkf3w%dCBuEd&FfP"},
		{"desert vista", "rWMi6#eufRH&HbqUwxdCYuvl&FNt"},
		{"library wall", "9dtiLxafae7cFbQUbz6iwcC4cCfP"},
		{"floral wall", "p4uQRHvi6rit8mcGDH&#zzdGTmxY"},
		{"tropical vista", "pOuQR2EN9wFW8DyyetVRzPnuz8xc"},
		{"playroom wall", "pOiQRF@i9#JT8DuVetVxiSmujoxc"},
		{"kitschy wall", "9qtiLxafaeR3FbQEb56imcCAcCfP"},
		{"groovy wall", "96Bipv&wl9IcFkZ3jNti&cC4bCfz"},
		{"mushroom mural", "pOuQRFEi9wFA8D5GetVxiDmujoxc"},
		{"ringside seating", "pOiQR2@N9#JF8DWBetVRzHnuz8xc"},
		{"harvest wall", "rW@i6PBfERP&Hbfw#xdCYuEnapfP"},

		// Carpet
		{"plush carpet", "NyiV4YZFtZS#NwhTTNo5MtRWg4Fy"},
		{"classic carpet", "5pBnKtxNFRJ%NHoteZvRn4bKJkte"},
		{"checkered tile", "tD&CpdFh23O6XYViAyTxQKLYGpOe"},
		{"old flooring", "XKVtcNoNdJHEgv@S%8AGcRZpc6x5"},
		{"red tile", "NZTu8xYFtMF#N#JTTNo5Me&kg4Jy"},
		{"birch flooring", "5pBlKtx8f7S%NHudeqVRn4bKJWeE"},
		{"classroom floor", "tD&CpdFh23O6XYViAyjxQKLYGFOe"},
		{"lovely carpet", "X5V#cNoftJiqgvvSY8AxcRMpc9x5"},
		{"exotic rug", "NZiu8xYFtQF#N#hTTNo5Me&Wg4Jy"},
		{"mossy carpet", "5IynKtxNSRJ%NHoteqvRn4bKJJeE"},
		{"18 mat tatami", "tD&ohdFhKEO6XYViAvaRQKLYGpmx"},
		{"8 mat tatami", "XKV#cNoftJirgvvSY8AxcRM2c9x5"},
		{"citrus carpet", "FyUuktYTPZF3onGbyEuzZp#Av4Oz"},
		{"cabin rug", "5pB3adxNf7J%NHoteEvRn4bKJJHE"},
		{"closed road", "tS&CpdFhKMO6XYViAljRQKLYGFCx"},
		{"lunar surface", "XKVtcNoNdJHEgv@S%8AGcRZpc6e5"},
		{"sand garden", "NyiV4YZFtZS#NwJTTNo5Me&kg4Fy"},
		{"spooky carpet", "5pB3adxNFRJ%NHoteMERn4bKJkPe"},
		{"western desert", "tS&yhdFsaxY6XYBXAvWRQKLYGFmx"},
		{"green rug", "X5VtcNoNdJHrgv@S%8AGcRZ2c6e5"},
		{"blue flooring", "FZUVktYTPZF3oBMbyEuzZp#Av4Zz"},
		{"regal carpet", "5IynKtxNf7J%NHoteqERn4bKJJeE"},
		{"ranch flooring", "tS&yhdFsKMY6XYBXAvWRQKLYGpmx"},
		{"modern tile", "X5V#cNoNtJHEgv@S%8AVcRZpc9x5"},
		{"cabana flooring", "NyTi8xYFtQF#NwhTTNo5Me&Wg4Fy"},
		{"snowman carpet", "5IynKtxNf7J%NHoteqvRn4bKJWeE"},
		{"backyard lawn", "tD&MpdFsKEY6XYBXAlfRQKLYGFCx"},
		{"music room floor", "X5V#cNoNtJirgv@SY8AxcRM2c9x5"},
		{"plaza tile", "FyEg%eYTPJF3onGbyEuzZp#Av4Oz"},
		{"kitchen tile", "5IylKtx8W7S%NHudeZVRn4bKJQte"},
		{"ornate rug", "tS&MpdFs2xY6XYBXAyfxQKLYGpOe"},
		{"tatami floor", "XKVtcNofdJirgvvSY8AMcRM2c6x5"},
		{"bamboo flooring", "FyUg%eYTPMF3onGbyEuzZI#Tv4Oz"},
		{"kitchen flooring", "5pB3adxNWRJ%NHoteMvRn4bKJQPe"},
		{"charcoal tile", "tS&MpdFsKMY6XYBXAlaRQKLYGpCx"},
		{"stone tile", "X5V#cNoftJirgvvSY8AxcRMpc9e5"},
		{"imperial tile", "NyTi8xYFtMF#NwJTTNo5Me&Wg4Fy"},
		{"opulent rug", "5pB3adxNWRJ%NHoteMERn4bKJkPe"},
		{"slate flooring", "tD&yhdFs23Y6XYBXAG2xQKLYGFF@"},
		{"ceramic tile", "X5V#cNoNtJi5gv@SY8AxcRM2c9x5"},
		{"fancy carpet", "FyEuktYTPZF3onGbyEuzZI#Av4Oz"},
		{"cowhide rug", "5pBlKtx8WRS%NHudeZxRn4bKJQte"},
		{"steel flooring", "tD&yhdFsKEY6XYBXAvWRQKLYGpmx"},
		{"office flooring", "XKVtcNofdJiEgvvSY8AMcRM2c6x5"},
		{"ancient tile", "FyUg%eYTPJF3onGbyEuzZI#Tv4Oz"},
		{"exquisite rug", "5IyEadx8fRS%NHudeEVRn4bKJJHE"},
		{"sandlot", "tD&CpdFhbMO6XYViAyTxQKLYGFOe"},
		{"jingle carpet", "X5V#cNoftJHqgvvS%8AVcRZpc9x5"},
		{"daisy meadow", "FZEe%eYTPMF3oBGbyEuzZp#Av4Zz"},
		{"sidewalk", "5pBlKtx8fRS%NHudeqxRn4bKJWeE"},
		{"mosaic tile", "tS&yhdFsbEY6XYBXAG2xQKLYGFF@"},
		{"parquet floor", "XKV#cNoNtJiEgv@SY8AxcRMpc9e5"},
		{"basement floor", "FyUuktYTPZF3onMbyEuzZI#Av4Oz"},
		{"chessboard rug", "5Iy3adxNS7J%NHoteEvRn4bKJJHE"},
		{"kiddie carpet", "tS&MpdFs23Y6XYBXAyaxQKLYGFOe"},
		{"shanty mat", "X5VtcNofdJiqgvvSY8AMcRM2c6e5"},
		{"concrete floor", "FZEVktYTPQF3oBGbyEuzZp#Av4Zz"},
		{"saharah's desert", "5pBEadx8WRS%NHudeMVRn4bKJkPe"},
		{"tartan rug", "tD&MpdFs23Y6XYBXAyaxQKLYGpOe"},
		{"palace tile", "X5V#cNoftJHqgvvS%8AVcRZ2c9x5"},
		{"tropical floor", "FZUVktYTPQF3oBMbyEuzZI#Av4Zz"},
		{"playroom rug", "5pBlKtx8FRS%NHudeZxRn4bKJQte"},
		{"kitschy tile", "tS&CpdFha3O6XYViAlTRQKLYGFCx"},
		{"diner tile", "XKV#cNoNtJirgv@SY8AxcRM2c9x5"},
		{"block flooring", "FyUuktYTPQF3onGbyEuzZp#Av4Oz"},
		{"boxing ring mat", "5Iy3adxNFRJ%NHoteMERn4bKJQPe"},
		{"harvest rug", "tD&ohdFhKMO6XYViAvaRQKLYGFmx"},

		// Clothes
		{"flame shirt", "eCb7l%UKQSrkrIk4qHQdQtfyDoy8"},
		{"paw shirt", "4@co68CW63Df7PdYt8lNn#xf464d"},
		{"wavy pink shirt", "l5dI2ZILZTsDEnWcKMf66FQdIREp"},
		{"future shirt", "nX#PWvCUVAUcB#VMt5bRwSVePDj%"},
		{"bold check shirt", "rOHmy%b5LWk&UGMdDoOKnPxdEvho"},
		{"mint gingham", "bQOIunl89K%k3bThh#qVYCJxrAcK"},
		{"bad plaid shirt", "l5dI2ZILZTsDEnWcbMf66FQdIREp"},
		{"speedway shirt", "gi#PcVCUiRUcB#VMd5O&sSVPPDT%"},
		{"folk shirt", "Wb5Q%Y&VxQ8OnYlCAlsowl7JAgpF"},
		{"daisy shirt", "4@co68wW63Qf7PdYt8lN2UTfAtRd"},
		{"wavy tan shirt", "LUW85EjwZPOimAlaBd9p&AOXkect"},
		{"optical shirt", "rFFApeGl&SW3GLZcsCFKygq4Lc58"},
		{"rugby shirt", "gu#P3V&uu9KqBzvMd8J7sUv7PmTf"},
		{"sherbet gingham", "bMDDdK6%2iWLUbxptZftE9OgsBqh"},
		{"yellow tartan", "rU3yGmEMB2vToindJ27SK4%XAX8n"},
		{"gelato shirt", "Wz5QqtCsgiuZnxBOAh@8s@&EAvpm"},
		{"work uniform", "rOimy%b5Lfk&UVMdDoOKlPxdEvho"},
		{"patched shirt", "&NrLXFGavhOikA@htEppi#xvRt3d"},
		{"red aloha shirt", "&83LXFGEvanNkAvhtE9pi#Zv&Hct"},
		{"blue aloha shirt", "rFFApeGl&SW3GLZcMCFb8gq4Lc5N"},
		{"dark polka shirt", "eCb7l%UKQSrkrPk4lHQdQtfyDoy8"},
		{"lite polka shirt", "ZMOQnvtInrWDw7%q7HW@qm%vwB%5"},
		{"lovely shirt", "b9DDDOd%2HuLUoApKZfeE9OnsBq5"},
		{"citrus shirt", "rFFApeGl&SW3GLZcyCFb8gq4Lc5N"},
		{"kiwi shirt", "gu#PWN&wg5KqBzv5d8Nww&vgPmTf"},
		{"watermelon shirt", "bMDDdd6%2iWLUbxp4ZfeE9OgsBq5"},
		{"strawberry shirt", "rU3yGmvsB7CToindJ2PSN4qWP48n"},
		{"grape shirt", "gi#PcVCUiRUcB#VMd5OUsfVPPDT%"},
		{"melon shirt", "rOHmy%b5LWk&UGMdDoObBPxdEvhu"},
		{"jingle shirt", "lhOIgc&IZVL%E25qjxf66FQ@IREa"},
		{"blossom shirt", "bIOIbc689d8o3oxhT#qBYCJYrAch"},
		{"icy shirt", "juC4wzRlUbKrvzEtPV%bO7f8k@NE"},
		{"crewel shirt", "gu#PkV&ugrKqBzvMd8h7w&vgPmTf"},
		{"tropical shirt", "bQOIuclD9K%k3bThF#qBYCJxrAca"},
		{"ribbon shirt", "LUW85EjwZHZimAlaBdvp&%OXkect"},
		{"fall plaid shirt", "rFFApeGl&SW3GLZcyCFb8gq4Qc5N"},
		{"fiendish shirt", "eCb7l%UKIK3krIk4lFQKQtfy%oy8"},
		{"chevron shirt", "bMDDdK6&2iWQUbxppYftE9OgsBqa"},
		{"ladybug shirt", "&83LXFG&vsONkAvhtEvpiUMv&Pct"},
		{"botanical shirt", "gi#PciCUijwcB#VZd5t&sSVPPDT%"},
		{"anju's shirt", "nN#PcV&wu9KqBzvrt8JwsUv7Pmjf"},
		{"kaffe's shirt", "ZMOQnvtInrWDw7%qvHW@qm%vwB%5"},
		{"lavender robe", "4dqo68Ck6xDW7PlYt8aun#Mf8Ijd"},
		{"blue grid shirt", "Wz5QqYCsg4NZnxBCAhMos@&EAvpm"},
		{"butterfly shirt", "kb5QEY&Ves8OnYlC%lQosl7MAgXF"},
		{"blue tartan", "rK3yGmvhBRCJoiOdJ2eSN4cWIzN6"},
		{"gracie's top", "l5dI2ZILZTs%EnWcGxf66FQdIREa"},
		{"orange tie-dye", "rFFApeGlDNW3G4ZcQeFO8gq4Qc5N"},
		{"purple tie-dye", "rOHmy%b5ygk&UGMdU4OdnPxd@vho"},
		{"green tie-dye", "lhOIgc&IZVLDE25qbMf66FQ@IREp"},
		{"blue tie-dye", "b9DDDOd&2HuLUoAp4ZfeE9OnsBq5"},
		{"red tie-dye", "juC4wzRlEOKrvzEtPg%SY7f8m@Nq"},
		{"one-ball shirt", "eCO7l%UKIb3krIk4qFQKAtfy%oy8"},
		{"two-ball shirt", "4@co68CW6cPf7PdYt86Nnrxf464d"},
		{"three-ball shirt", "b9DDDOd%2HuQUoApcZfeE9OnsBqK"},
		{"four-ball shirt", "rFFApeGl&SW3GLZcsCFb8gq4Lc5N"},
		{"five-ball shirt", "rOHmy%b5ygk&UVMdU4OOBPxd@vhu"},
		{"six-ball shirt", "&NrLXFMavhtikA@htEppzrAvP6wd"},
		{"seven-ball shirt", "LUW85ETCZmBimAlaBd9pvAmio6qt"},
		{"eight-ball shirt", "gi#PWNCUVTwcB#VZd5zUwSVePDT%"},
		{"nine-ball shirt", "gu#PWv&wgrKqBzvrd8hww&vgPmTf"},
		{"arctic camo", "4@co68w263If7PdYt8lN2UAfAeRd"},
		{"jungle camo", "rU3yGmvMB7gToindJ2PSN4EXPi8n"},
		{"desert camo", "rFFApeGlDNW3G4ZcyeFO8gq4Qc5N"},
		{"rally shirt", "rOimy%b5yvk&UVMdU4OdlPxd@vho"},
		{"racer shirt", "&NrLXFGavsOikA@htEapiUxvRtwd"},
		{"racer 6 shirt", "b9DDDOd&2HuQUoApcZfeE9OnsBqK"},
		{"fish bone shirt", "rFFApeGl&SW3GLZcQCFb8gq4Qc5N"},
		{"spiderweb shirt", "Wb5Qfq&RxQ8OnYl3Alskwl7JAgpF"},
		{"zipper shirt", "&NrLXFGav&OikA@htEapiUxvRt3d"},
		{"bubble shirt", "LUW85ETCZmBimAlaBd9pvAmio6Kt"},
		{"yellow bolero", "Wz5QqtCsgiuZnxBOAh@osE&EAvpm"},
		{"nebula shirt", "nN#PkV&ugrKqBzvMt8hww&vgPmjf"},
		{"neo-classic knit", "lhOIgn&LZVLDE25qdMf96FQ@IREh"},
		{"noble shirt", "b9DDDbd%2HuLUoApHYftE9OnsBqh"},
		{"turnip top", "rFFApeGlDNW3GLZcQeFdygq4Qc58"},
		{"oft-seen print", "eCO7l%UKIb3krPk4qFQbmtfyDoyN"},
		{"ski sweater", "LKW85ETbZHdXmAdaBdapv%Ji8I3d"},
		{"circus shirt", "l5dI2ZIIZTsDEnWcKMf66FQdIREp"},
		{"patchwork top", "kz5QqtCsgiuZnxBO%h@os@&EAvXm"},
		{"mod top", "nN#PWv&wgrKqBzvrt8h7wUvgPmjf"},
		{"hippie shirt", "ZMOQnvtInrW%w7%qPHW@qm%vwB%q"},
		{"rickrack shirt", "b9DDDbd&2HuQUoAp2YftE9OnsBqa"},
		{"diner uniform", "nX#PciCUijwcB#VZt5tRsSVPPDj%"},
		{"shirt circuit", "Wb5Q%t&VxJoOnYlOAl8owl7JAgpF"},
		{"u r here shirt", "LKW85ETOZHlXmAdaBdapv%Qi8p3d"},
		{"yodel shirt", "l5dI2ZILZTs%EnWcjxf66FQdIREa"},
		{"pulse shirt", "juC4wzRlUbKrv5EtPV%KY7f8k@Nq"},
		{"prism shirt", "nN#P3V&uu9KqBzvMt8Jws&v7Pmjf"},
		{"star shirt", "&NrLXFGav&OikA@htEapiUxvRtwd"},
		{"straw shirt", "l5dI2yIIZTs%EnWcYMf96FQdIREK"},
		{"noodle shirt", "gi#PcVCUiRUcB#VMd5ORsfVPPDT%"},
		{"dice shirt", "gu#Pki&ug5KqBzvZd8N7wUvgPmTf"},
		{"kiddie shirt", "rK3yGmvZBRgJoiOdJ2eSN43XI#f6"},
		{"frog shirt", "Z9OQ73OIn9uDwgqqEHWdqm%lwB%h"},
		{"moody blue shirt", "nX#PcVCUiRUcB#VMt5ORsfVPPDj%"},
		{"cloudy shirt", "rOimy%b5yvk&UGMdD4OOyPxdEvhu"},
		{"fortune shirt", "4@co68C263&f7PdYt8lNn#Yf494d"},
		{"skull shirt", "b9DDDbd&2HuLUoApHYftE9OnsBqh"},
		{"desert shirt", "juC4wzRlUbKrvzEtzV%KY7f8m@Nq"},
		{"aurora knit", "rOHmy%b5ygk&UVMdD4OOBPxd@vhu"},
		{"winter sweater", "&NrLXFMqvaBikA@htEppzrTgP9wd"},
		{"go-go shirt", "LUW85ETwZmtimAlaBd9pvAFio9bt"},
		{"jade check print", "kz5QfdCsCeuZnxBO%hU%w@&fAvXm"},
		{"blue check print", "Wb5QEt&VehoOnYlOAlDosl7MAgpF"},
		{"red grid shirt", "bQOIucl89K%o3bThE#qBYCJxrAch"},
		{"flicker shirt", "b9DDDOd&2HuQUoApkZfeE9OnsBqK"},
		{"floral knit", "rFFApeGl&SW3G4ZcMCFb8gq4Lc5N"},
		{"rose shirt", "rOimy%b5yvk&UVMdD4OOyPxdEvhu"},
		{"sunset top", "rK3yGmvZB29JoiOdJ2gSN83XI#f6"},
		{"chain-gang shirt", "Z9OQ73OLn9uDwgqqkHWdqm%lwB%h"},
		{"spring shirt", "juC4wzRlEOKrvzEt4g%SY7f8m@Nq"},
		{"bear shirt", "kb5Qfd&RxJoOnYlc%l8owl7JAgXF"},
		{"mvp shirt", "rK3yGmEZBjvJoiOdJ2gSK4kXQrN6"},
		{"silk bloom shirt", "&83LXFGEvsnNkAvhtEvpiUZv&Hct"},
		{"pop bloom shirt", "juC4wzRlUbKrv5Et4V%KY7f8k@Nq"},
		{"loud bloom shirt", "kb5QEt&VehoOnYlO%lDksl7MAgXF"},
		{"hot spring shirt", "rK3yGmEZB7VJoiOdJ2eSKLkXQrN6"},
		{"new spring shirt", "bIOIbc6D9d8o3oxhf#qBYCJYrAch"},
		{"deep blue tee", "rFFApeGl&SW3G4ZcQCFb8gq4Lc5N"},
		{"snowcone shirt", "rOHmy%b5ygk&UVMdD4OOBPxdEvhu"},
		{"ugly shirt", "LKW85EjOZH6XmAdaBdap&%Mi%H3d"},
		{"sharp outfit", "&83LXFM&vatNkAvhtE9pzrQvDIbt"},
		{"painter's smock", "juC4wzRlEOKrv5Ettg%SY7f8m@Nq"},
		{"spade shirt", "nN#PkV&ugrKqBzvMt8h7w&vgPmjf"},
		{"blossoming shirt", "bQOIunlD9K%o3bThV#qVYCJxrAc5"},
		{"peachy shirt", "l5dI2yILZTs%EnWcZMf96FQdIREK"},
		{"static shirt", "Wz5QqYCsg4NZnxBCAhMosE&EAvpm"},
		{"rainbow shirt", "nN#PcV&wu9KqBzvrt8Jws&v7Pmjf"},
		{"groovy shirt", "4@co68CW6YPf7PdYt86Nnrxf46Rd"},
		{"loud line shirt", "l5dI2ZIIZTsDEnWcuxf66FQdIREp"},
		{"dazed shirt", "kz5QfqCsCtNZnxBC%hG%wE&fAvXm"},
		{"red bar shirt", "kb5QEt&VehoOnYlO%lDks87MAgXF"},
		{"blue stripe knit", "lhOIgn&LZVL%E25qJxf96FQ@IREK"},
		{"earthy knit", "4dqo68w76c7W7PlYt8pu2#Qf%Hid"},
		{"spunky knit", "gi#PcVCUiRUcB#VMd5OUsSVPPDT%"},
		{"deer shirt", "nN#Pci&wu6KqBzv5t8S7s&v7Pmjf"},
		{"blue check shirt", "bQOIunlD9K%o3bThj#qVYCJxrAc5"},
		{"light line shirt", "4dqo68w76xIW7PlYt8au2UQf%Hjd"},
		{"blue pinstripe", "Wz5QqYCsg4NZnxBCAhM%sE&EAvpm"},
		{"diamond shirt", "eCb7l%UKQSrkrPk4qHQdQtfyDoy8"},
		{"lime line shirt", "rK3yGmvZBj9JoiOdJ2gSN83XI#N6"},
		{"big bro's shirt", "l5dI2ZILZTs%EnWcVxf66FQdIREa"},
		{"green bar shirt", "gi#PciCUijwcB#VZd5tRsfVPPDT%"},
		{"yellow bar shirt", "Wb5Qfd&RxJoOnYlcAl8kw87JAgpF"},
		{"monkey shirt", "bMDDdK6%2iWLUbxpSYftE9OgsBqh"},
		{"polar fleece", "4dqo68C76x&W7PlYt8aun#Zf8pjd"},
		{"ancient knit", "juC4wzRlEOKrv5Et4g%SY7f8k@Nq"},
		{"fish knit", "rOHmy%b5LWk&UGMdUoObBPxd@vhu"},
		{"vertigo shirt", "ZMOQnEtLnrWDw7%q3HWdqm%vwB%h"},
		{"misty shirt", "LUW85ETCZFlimAlaBdvpv%mio6qt"},
		{"stormy shirt", "gi#PciCUijwcB#VZd5tUsSVPPDT%"},
		{"red scale shirt", "eCb7l%UKQSrkrIk4lHQdQtfy%oy8"},
		{"blue scale shirt", "4@co68CW6cPf7PdYt86Nnrxf46Rd"},
		{"heart shirt", "&83LXFGEvhnNkAvhtE9pi#Zv&Hct"},
		{"yellow pinstripe", "gi#PcVCUiRUcB#VMd5O#sSVPPDT%"},
		{"club shirt", "rOimy%b5Lfk&UVMdUoOKlPxdEvho"},
		{"li'l bro's shirt", "bMDDdd6%2iWLUbxp8ZfeE9OgsBq5"},
		{"argyle knit", "LUW85EjCZPnimAlaBd9p&ACiktKt"},
		{"caveman tunic", "nX#PciCUijwcB#VZt5t#sfVPPDj%"},
		{"café shirt", "rOimy%b5Lfk&UGMdUoOKlPxd@vho"},
		{"tiki shirt", "&NrLXFMavhtikA@htEppzrAvP63d"},
		{"a shirt", "4dqo68C76YRW7PlYt8punrZf8pid"},
		{"checkered shirt", "rFFApeGl&SW3G4ZcsCFb8gq4Qc5N"},
		{"no.1 shirt", "kb5QEY&Ves8OnYlC%lQos87MAgXF"},
		{"no.2 shirt", "ZMOQnvtLnrWDw7%qgHW@qm%vwB%5"},
		{"no.3 shirt", "4dqo68w76Y7W7PlYt8pu2#Qf%Hid"},
		{"no.4 shirt", "rFFApeGl&SW3G4ZcyCFKygq4Lc58"},
		{"no.5 shirt", "gu#PkV&ugrKqBzvMd8hwwUvgPmTf"},
		{"no.23 shirt", "ZMOQnvtLnrW%w7%qPHW@qm%vwB%q"},
		{"no.67 shirt", "LUW85ETwZFdimAlaBdvpv%Fio9bt"},
		{"bb shirt", "Wz5QqYCsg4NZnxBCAhMks@&EAvpm"},
		{"beatnik shirt", "rOHmy%b5ygk&UGMdD4OdnPxd@vho"},
		{"moldy shirt", "ZMOQnEtLnrW%w7%qLHWdqm%vwB%K"},
		{"houndstooth tee", "rU3yGmEsBReToindJ2PSKLfXAL8n"},
		{"big star shirt", "Wz5QqtCsgiuZnxBOAh@os@&EAvpm"},
		{"orange pinstripe", "nN#Pki&ug5KqBzvZt8Nww&vgPmjf"},
		{"twinkle shirt", "rK3yGmEZBRVJoiOdJ2eSKLkXQrf6"},
		{"funky dot shirt", "l5dI2yIIZTsDEnWcSxf96FQdIREh"},
		{"crossing shirt", "juC4wzRlEOKrv5Et4g%FO7f8k@NE"},
		{"splendid shirt", "eCO7l%UKQFrkrPk4lHQdAtfy%oy8"},
		{"jagged shirt", "LKW85EjbZHZXmAdaBdap&%ZX%Pwd"},
		{"denim shirt", "bIOIbn689d8o3oxhv#qVYCJYrAc5"},
		{"cherry shirt", "juC4wzRlUbKrvzEtPV%KY7f8k@Nq"},
		{"gumdrop shirt", "eCb7l%UKQSrkrIk4lHQODtfyDoyN"},
		{"barber shirt", "bMDDdd6&2iWLUbxpKZfeE9OgsBq5"},
		{"concierge shirt", "rU3yGmEsBj@ToindJ27SK4fXAL%n"},
		{"fresh shirt", "juC4wzRlUbKrvzEt4V%KY7f8k@Nq"},
		{"far-out shirt", "eCO7l%UKQFrkrIk4qHQOmtfy%oyN"},
		{"dawn shirt", "&NrLXFMqvsBikA@htEapz#TgP9wd"},
		{"striking outfit", "l5dI2yIIZTsDEnWcFxf96FQdIREh"},
		{"red check shirt", "rFFApeGl&SW3G4ZcQCFKygq4Qc58"},
		{"berry gingham", "Wb5Qfd&RxJoOnYlcAl8owl7JAgpF"},
		{"lemon gingham", "ZMOQnEtInrWDw7%q%HWdqm%vwB%h"},
		{"dragon suit", "rU3yGmEsB2@ToindJ27SK4fXAL8n"},
		{"g logo shirt", "kz5QfqCsCtNZnxBC%hGkwE&fAvXm"},
		{"tin shirt", "gu#Pki&ug5KqBzvZd8N7w&vgPmTf"},
		{"jester shirt", "&NrLXFMqvhBikA@htEppzrTgP9wd"},
		{"pink tartan", "b9DDDbd&2HuLUoApdZftE9OnsBqh"},
		{"waffle shirt", "Wz5QqtCsgiuZnxBOAh@ks@&EAvpm"},
		{"gray tartan", "gu#P3i&uu6KqBzvZd8S7sUv7PmTf"},
		{"windsock shirt", "rK3yGmEhB7eJoiOdJ2eSKLWXQ5N6"},
		{"trendy top", "b9DDDOd%2HuQUoAp5ZfeE9OnsBqK"},
		{"green ring shirt", "juC4wzRlEOKrvzEttg%FO7f8k@NE"},
		{"white ring shirt", "rOHmy%b5LWk&UVMdDoOKnPxd@vho"},
		{"snappy print", "4@co68wW6xQf7PdYt8lN2UTfAt4d"},
		{"chichi print", "b9DDDOd%2HuQUoApkZfeE9OnsBqK"},
		{"wave print", "kz5QqYCsg4NZnxBC%hMksE&EAvXm"},
		{"checkerboard tee", "kb5Qfq&RxQ8OnYl3%lskw87JAgXF"},
		{"subdued print", "bQOIuclD9K%o3bThE#qBYCJxrAch"},
		{"airy shirt", "&83LXFGEvanNkAvhtE9pi#Zv&Hbt"},
		{"coral shirt", "juC4wzRlUbKrv5EttV%bO7f8m@NE"},
		{"leather jerkin", "rOHmy%b5LWk&UGMdUoObBPxdEvhu"},
		{"zebra print", "&NrLXFMavatikA@htEppzrAvP63d"},
		{"tiger print", "bIOIbc689d8k3oxhM#qBYCJYrAca"},
		{"cow print", "Wz5QfdCsCeuZnxBOAhU%wE&fAvpm"},
		{"leopard print", "kb5Q%Y&VxQ8OnYlC%lsow87JAgXF"},
		{"danger shirt", "bMDDdK6%2iWLUbxpdZftE9OgsBqh"},
		{"big dot shirt", "&83LXFGEv&nNkAvhtEvpiUZv&Hct"},
		{"puzzling shirt", "rFFApeGl&SW3G4ZcyCFb8gq4Lc5N"},
		{"exotic shirt", "kb5QEY&Ves8OnYlC%lQksl7MAgXF"},
		{"houndstooth knit", "ZMOQnEtInrWDw7%q3HWdqm%vwB%h"},
		{"uncommon shirt", "rU3yGmvMB7gToindJ2PSN4EXPi%n"},
		{"dapper shirt", "juC4wzRlEOKrv5EtPg%FO7f8k@NE"},
		{"gaudy sweater", "gu#PWN&wg5KqBzv5d8N7w&vgPmTf"},
		{"cozy sweater", "&NrLXFGavaOikA@htEppi#xvRtwd"},
		{"comfy sweater", "LUW85EjCZF6imAlaBdvp&%Ciktqt"},
		{"classic top", "rFFApeGlDNW3G4ZcyeFdygq4Lc58"},
		{"vogue top", "Wb5Q%Y&VxQ8OnYlCAlskwl7JAgpF"},
		{"laced shirt", "LKW85EjOZF6XmAdaBdap&%Mi%Hwd"},
		{"natty shirt", "bIOIbn6D9d8k3oxhG#qVYCJYrAcK"},
		{"citrus gingham", "rFFApeGl&SW3GLZcsCFKygq4Qc58"},
		{"cool shirt", "eCO7l%UKQFrkrIk4lHQOmtfy%oyN"},
		{"dreamy shirt", "rK3yGmvhBjMJoiOdJ2gSN8cWIzN6"},
		{"flowery shirt", "LUW85EjCZmnimAlaBd9p&ACiktKt"},
		{"caterpillar tee", "juC4wzRlUbKrv5EttV%bO7f8k@NE"},
		{"shortcake shirt", "rOimy%b5yvk&UGMdU4OOyPxd@vhu"},
		{"whirly shirt", "4@co68wW6Ymf7PdYt86N2#TfAtRd"},
		{"thunder shirt", "b9DDDbd&2HuQUoAp6ZftE9OnsBqa"},
		{"giraffe print", "Wz5QfqCsCtNZnxBCAhG8w@&fAvpm"},
		{"swell shirt", "nN#Pki&ug5KqBzvZt8N7w&vgPmjf"},
		{"toad print", "bMDDdK6%2iWQUbxp2YftE9OgsBqa"},
		{"grass shirt", "Z9OQ73OIn9u%wgqqLHWdqm%lwB%K"},
		{"mosaic shirt", "kz5QqYCsg4NZnxBC%hMosE&EAvXm"},
		{"fetching outfit", "gu#PkV&ugrKqBzvMd8h7wUvgPmTf"},
		{"snow shirt", "&NrLXFGqvhnikA@htEppi#YvRewd"},
		{"melon gingham", "4dqo68C76x&W7PlYt8aun#Zf8pid"},

		// Handheld Items
		{"gelato umbrella", "WqlALXHFXShGARtYutd#2QrL8EmY"},
		{"daffodil parasol", "yQPJegjap4a7BpH&&yEY&EdrAi9c"},
		{"berry umbrella", "KuOTG8ZrJmV#Jst4JSI7&&OovmU4"},
		{"orange umbrella", "edybyjquJeeNbYTKc7umK5zPSMBj"},
		{"mod umbrella", "7q8z6PMSZXRVKIqpXwAprLSFWEVp"},
		{"petal parasol", "KJujnFBVnvMYPxN%XJbDw%6rzsn8"},
		{"ribbon parasol", "KJuaupVvgyCYPElfFQyDsQge#Q7o"},
		{"gingham parasol", "JE7Amhn65HBckM&bMe9UgghS%&uZ"},
		{"plaid parasol", "rqbbyjMJJ#RubTfqnkiP55YHfMBj"},
		{"lacy parasol", "KV@Xm2&ZTV6mhz6OTIqcXWFenPcO"},
		{"elegant umbrella", "KpuabFVfgGMYPTK%FQyDsJ9z#s7o"},
		{"dainty parasol", "ESBc4jYVWt6gc9AJZ3crz63L2vvp"},
		{"classic umbrella", "W%lALXtNXSrrARvqutSUWMw88MmY"},
		{"nintendo parasol", "Kpua7FBTnvMYPTa%XJbDwft5zsn8"},
		{"bumbershoot", "2odH8NYqJmg#QPtKJSI7&&duvmN4"},
		{"sunny parasol", "fE7AmGnlcHP9ksPbMe9&g7hp%suZ"},
		{"batbrella", "rqbbBjxJQrRubJfYnkTP55YHfEja"},
		{"checked umbrella", "GAPpegjaa4p7RPp&GyvY&qtrA43c"},
		{"yellow umbrella", "KJuaoFBVnlCYPEK%FJyDs%ge#Qno"},
		{"leaf umbrella", "rdoz6PqiZpeGK9qJ9CkDULfmFEVp"},
		{"lotus parasol", "7q8znHMSMiRVKPqjrb45r6SFWMjp"},
		{"paper parasol", "GAPpegjaa4p7RPp&uyvY&qtrA43c"},
		{"polka parasol", "KpuawFBTnvMYPTlfFJyDsf9z#sno"},
		{"sharp umbrella", "f%7AmGn%5HPIksPbMep&g7ip%&uZ"},
		{"twig parasol", "TqlAL5dJXSr5AxvqutdRWMr88MmY"},
		{"noodle parasol", "G%Ppegjaa#a7BspavyvY&EdrAT9c"},
		{"hypno parasol", "ULdHy8ZqJmg#JRt4JSp7&adovmtL"},
		{"pastel parasol", "JE7Amhn6cHBkkM&bMe9UgghS%suZ"},
		{"retro umbrella", "#qbbyjEJf#PNbTfZnkiF55YHfMBj"},
		{"icy umbrella", "KG@Xm2&ZTR6mhjtCTIqcXWFenAcO"},
		{"blue umbrella", "KpujwFBTnvMYPTKAJJbDsf65#sn8"},
		{"flame umbrella", "rdoznPYiMHeGKeqH9CoSULfmFMjp"},
		{"bluebell fan", "WqlALXFFXSrJARlYutd#2Mr88EmY"},
		{"plum fan", "KJuanFBVnvMYPxafXJbDw%6rzsn8"},
		{"bamboo fan", "UXOTo8ZrJmV#Jst4JSp7&aOovme4"},
		{"cloud fan", "edybyRquJeeNbYTKWhXwKpKPSMBj"},
		{"maple fan", "Iq8z6PESqXPGKIqpXw4DrLSFWEVp"},
		{"fan fan", "G%Ppegjaa#p7RRpaGyvY&qtrAA3c"},
		{"flower fan", "KuOHo8ZrJmV#Jst4JSI7&&OovmU4"},
		{"leaf fan", "ESBc4jYVWt6gc9AJZ3brz63L2vvp"},
		{"yellow pinwheel", "#qbbBR3J%rPNbJfY2JNb5pqHfEja"},
		{"red pinwheel", "Kpuj2pVfgGMYPTafXQbDwJt5zs78"},
		{"tiger pinwheel", "KJuaupVvgGMYPxK%FQyDsQg##s7o"},
		{"green pinwheel", "edybBRcuQ9eNbZTbWhXbKpKPSEja"},
		{"pink pinwheel", "rqbbBRxJQrRubJfY2Jfz5pqHfEja"},
		{"striped pinwheel", "UV@Xm2&ZFRlmGs6CcmlcXkFenT6O"},
		{"flower pinwheel", "KodHu8ZqJmg#JRt4JSI7&&dovmKL"},
		{"fancy pinwheel", "fE7AmGtlcHH9ksPbMe9Ug7hp%suZ"},
		{"red balloon", "#qbbyREJf#PNbTfZ2Jfb5pqHfMBj"},
		{"yellow balloon", "KJujnFBVnvMYPxNkWJyDw%9#zsno"},
		{"blue balloon", "KpujwFBTnvMYPTK%FJyDsf9z#sno"},
		{"green balloon", "J%7AmhtLcHVLkM&bMepUggiS%suZ"},
		{"purple balloon", "T%lAL5dGXSr5AxvqutS&WMw88MmY"},
		{"bunny p. balloon", "Kpuj2pVfgGMYPTN%XQbDwJt5zs78"},
		{"bunny b. balloon", "bNOHo8ZrJmV#JIt8JSI7&&OuvmU4"},
		{"bunny o. balloon", "JE7Amht6cHBkkM&bMe9&gghS%suZ"},
		{"golden net", "icT87f9bWTF%%EuTCwZaBgevaHh7"},
		{"golden axe", "vEaKxf&kPBbz3ez&rtT87oDH5uFD"},
		{"golden shovel", "vMfKxWInDjcY34zULYT8xoD25bSD"},
		{"golden rod", "qYVA6sQaPkbjOK8NEtRt6nXYmgqr"},
		{"net", "&PTf7Oa6PE3wzIEMbuI8J74c&pVZ"},
		{"axe", "ulLVR#L2jq6E76eD6q9hpuKoAXk8"},
		{"shovel", "PmVR4ii#qv4fpkJ9kLD&NhO3Riro"},
		{"fishing rod", "%ni@uXCZZNQ&&IJDODOKtwN6dZxY"},

		// Stationery
		{"airmail paper", "Nd6hEHUiR3SPdDgSfzyaB2kw%Xg7"},
		{"sparkly paper", "6dRhoMQ7kPgQm8gjEsRAybYsDrg7"},
		{"bamboo paper", "n%VamoKvmx9Dn%9h5sBBVbfUPLPR"},
		{"orange paper", "nlVamLdomxpP7D9ZKxV@&of@@6P7"},
		{"essay paper", "@llSeURHU8Oll@phRHMyKbERlM9L"},
		{"panda paper", "tlVamLdGmc2D7%9ZKMBeVnfUDLP7"},
		{"ranch paper", "nfVamoKBmx9Dn%ghrsVlV2WUPLPR"},
		{"steel paper", "l@&hoxQ7kF9km%EjqRPA5bYM@IgV"},
		{"blossom paper", "Nd6hESULR3SAdDvS%z924b%w%XgR"},
		{"vine paper", "G%lSeUAFUNFy&EFhjiM9gG3xns9r"},
		{"cloudy paper", "n%VamoKvm39Dn%9h5sBVV2WUDLPR"},
		{"petal paper", "nlVam4dGm3pA7DxZUxtt#of@e6PV"},
		{"snowy paper", "nN&huMhDkD7QO%9TZARPjJlMDIgT"},
		{"rainy day paper", "6@&hoMQpkmgQm89jqsjTybYsmrg7"},
		{"watermelon paper", "Nd6hESUiRcH%d%vS%56a4b%w%XgR"},
		{"deep sea paper", "F86hqpd8RM@DDD9SQHVFaG7CE9gx"},
		{"starry sky paper", "@llSeURHUNOll@phRHMyK23RlM9L"},
		{"daisy paper", "J86hEp@uR3@DD%9SQpBSBgkw%XgR"},
		{"bluebell paper", "@vlSe#RIU8OolEShRp6Gah3RnM98"},
		{"maple leaf paper", "nlVam4dGmxpA7DVZUxttUof@e6PR"},
		{"woodcut paper", "nN&huEhDkSIQO%9TqAPHyulsmrgx"},
		{"octopus paper", "6@&hoxQpkH9Lm8vjqsHALcYsDrgR"},
		{"festive paper", "nfVam4KBmcgDn%ghUsev&bf@D6PV"},
		{"skyline paper", "u%lStUTJUoFy&@NhRiM6vXgx&s99"},
		{"museum paper", "@llSe#RHU8O8l@ShRH9yah3RlM98"},
		{"fortune paper", "J86hES@uRYeDD%9S%ptSaGkC%9gV"},
		{"stageshow paper", "l8Rho3sPkm7QO8gTMQRHjXqMmIgV"},
		{"thick paper", "u%lStUTJUoFy&@NhRiM9vGgx7s99"},
		{"spooky paper", "6%VaF8UlmM9DnD9hKRelVbaUPLPx"},
		{"noodle paper", "6dRhoMQ7kPgQm8gjEsRAycYsDrg7"},
		{"neat paper", "n%Vam4Kvmx9Dn%9hKstBV2WUPLPR"},
		{"horsetail paper", "nlVamLdom3pP7DrZKxV@Rof@@6Pg"},
		{"felt paper", "6%VaF8UgmZgDnDghURtB&22@P6PT"},
		{"parchment", "6@&hoxQpkmgLm8vjqsHALcYsDrgR"},
		{"cool paper", "nfVamoKBmYgDn%ghrsVv&bf@D6PV"},
		{"elegant paper", "u%lStUTmU4Fy&@FhjNZ9gXgx7s9I"},
		{"lacy paper", "nN&huMhFkSIQO%gTMAjPyWlsDrgx"},
		{"polka-dot paper", "6@&hoMQpkF9Qm89jqsjTycYsmrg7"},
		{"dizzy paper", "N@6hEHULRxSDd%gSf5G7Bb%wAXg7"},
		{"rainbow paper", "F86hqpd8RM@DDDrSQHVmjX7Cx9gT"},
		{"hot neon paper", "6%VaF8UlmqgDnD9hKRel&ba@P6PT"},
		{"cool neon paper", "J86hEp@uRceDD%9SQpBDaGkCA9gV"},
		{"aloha paper", "N@6hESULRYH%d%VSf5974b%wAXgR"},
		{"ribbon paper", "l@&hoxQpkH9km%xjERHA5cYM@IgV"},
		{"fantasy paper", "@llSe#RHULO8l@ShRH9ya5ERlM98"},
		{"woodland paper", "6dRhoxQ7kmgLm8VjEsPALbYsDrgR"},
		{"gingko paper", "nfVam4KBmx9Dn%ghUselV2WUPLPR"},
		{"fireworks paper", "nlVamLdom3pP7DrZKxV@Rnf@@6Pg"},
		{"winter paper", "@llSeURHU8Oll@phRHMGKbERnM9L"},
		{"gyroid paper", "tlVamLdGm3pD7%9ZKMBtVnfUPLP7"},
		{"ivy paper", "@vlSeURIULOnlEphRpZyK23RlM9L"},
		{"wing paper", "u%lStUTJU4Fy&@NhRiM9vXgx7s99"},
		{"dragon paper", "nN&huMhFkSIQO%gTMAjHyulsmrgx"},
		{"tile paper", "G%lSeUAFUXFy&EFhjiM6gG3xls9r"},
		{"misty paper", "@llSeURHULOnlEHhjHMGKbERnM9L"},
		{"simple paper", "l@&hoxQpkH9km%xjERHA5bYM@IgV"},
		{"honeybee paper", "6%VaFLUlmqgDnD9h5RVl&ba@P6PT"},
		{"mystic paper", "G%lSerAFUNFy&EFhbX96gG3xls9r"},
		{"sunset paper", "Nd6hESUiRxS%d%vS%56a42kw%XgR"},
		{"lattice paper", "nlVam4dom3pA7DvZKxe@Uof@@6PR"},
		{"dainty paper", "6%VaF8UgmZgDnDghURtV&22@D6PT"},
		{"butterfly paper", "JN6hEp@8RceDD%gSJpVmaGkCA9gV"},
		{"new year's card", "l8RhoxsPkHIQO8gTEQPHyWqsmrgR"},
		{"inky paper", "nlVam4dGmxpA7DVZUxteUnf@@6PR"},

		// Gyroids
		{"mini gargloid", "JTmu3Z2H3Jo#FYxDeynaCRVPaWge"},
		{"gargloid", "HrqIx#2eDx3r5iRBvE%jPVyfMMxa"},
		{"tall gargloid", "aL&D9Wkfsob4Im#M7Z@WZjow@#ER"},
		{"mini warbloid", "ar&D9Wkfw4b4IF#M7ZD2Jl&w@PxR"},
		{"warbloid", "HrqIx#2eDx3r5iRBvE%jPBhWMMx2"},
		{"tall warbloid", "Aw#QkxaPwj#9dt8YK#YtIVqXGCA2"},
		{"mini freakoid", "pL&D9k%fwobiIm#M7Z@WZB83@#xR"},
		{"mega freakoid", "Aw#QkxaPuj#9dt8YK#YtIB%XGCAa"},
		{"mini echoid", "l@sk6WOfWD2ONl2fB3TmNs4e&Opi"},
		{"mega echoid", "JTmu7yFH3Mo#FYxDeynaCRxPaWge"},
		{"tall echoid", "JTmu7yFH3Mo#FYxDgynaCRxIaWge"},
		{"mini gongoid", "JTmu3MpH3fo#FYxD2ynaCx#PaWge"},
		{"mega gongoid", "l@sk6WCWWD2ONl2XV3TmNs4eRm2i"},
		{"gongoid", "lEskrWCWWD2ONSpXV3km9sAtRO2i"},
		{"tall gongoid", "JTmu3Z2H3Jo#FYxD@ynaCRVPaWge"},
		{"mini poltergoid", "pL&DJk%vwobiIF#M7Z@WOj83@#ER"},
		{"mega poltergoid", "pr&D9k%fs4biIF#M7ZD2Ja73@PER"},
		{"poltergoid", "pr&DJk%vs4biIm#M7ZD2Fa&3@PxR"},
		{"tall poltergoid", "pL&DJk%vsobiIm#M7Z@WOB43@#xR"},
		{"mini lamentoid", "pL&DJk%vsobiIF#M7Z@WOB43@#ER"},
		{"mega lamentoid", "AwrQkxaPwT#9dt8YK#YzIB8XGCAa"},
		{"lamentoid", "aL&DJWkvsob4IF#M7Z@WOj8w@#xR"},
		{"tall lamentoid", "AwrQkxaPuT#9dt8YK#YzIBKXGCA2"},
		{"mini metatoid", "HrcIx#2e@V3r5iRBvE%YPVXWMMxa"},
		{"metatoid", "J5xDpx2U##%@6jKOUd3J&zBMAIEW"},
		{"mini squelchoid", "TaHCINAyxv4w#AOG6o#4U@wOKTlv"},
		{"mega squelchoid", "TapCIuAyxqLw#AOG6n#4UDwOKTlv"},
		{"squelchoid", "#g96QvVNLqQ4exa5fXj@emv2dzqu"},
		{"mini fizzoid", "l@skLWOfWD2ONd2fB3WmXsAe&Fpi"},
		{"mega fizzoid", "lEskIWOfWD2OUapXV3Am@s4tRO2i"},
		{"mini plinkoid", "TaHCpuxhxv4s#AOy6o#4U@wOKTl@"},
		{"mega plinkoid", "5ge6QaVNLqQAtxa5fXj@gCv2dzlu"},
		{"plinkoid", "faHCpXAhxEsw#AOs6n#4rDGOKTnv"},
		{"mini croakoid", "J5xDpx2U##%@6jKOUd3J&#BMAIEf"},
		{"mega croakoid", "J5EDpx2U#e%@6jKOUd3h&#ixAIEf"},
		{"croakoid", "pL&DJk%vsobiIF#M7Z@WOj83@#ER"},
		{"tall croakoid", "ar&D9Wkfs4b4Im#M7ZD2Jl&w@PER"},
		{"mini strumboid", "5g96QaVNLEIQtxarfXu@g9v2Kzlu"},
		{"mega strumboid", "5Ve6QaVULqIDtxjrfXuDg9v2aKlu"},
		{"strumboid", "#Ve6QvVULEQkexj5fXjDemv2qzqu"},
		{"tall strumboid", "#g96QvVNLEQLexarfXu@eIv2Kzqu"},
		{"mini rustoid", "rge6QaVNLqQ4txa5fXj@gmv2dzqu"},
		{"mega rustoid", "AwrQkxaPuT#9dt8YK#YzIVKXGCA2"},
		{"rustoid", "pL&DJk%vsobiIF#M7Z@WOB43@#xR"},
		{"mini buzzoid", "Aw#QkxaPuj#9dt8YK#YtIBqXGCAa"},
		{"mega buzzoid", "AwrQkxaPwT#9dt8YK#YzIVKXGCA2"},
		{"buzzoid", "HrcIx#2eDV3r5iRBvE%YPB5fMMx2"},
		{"tall buzzoid", "J5EDpx2Uie%@6jKOUd3h&#ixAIEf"},
		{"mini timpanoid", "ar&D9Wkfw4b4Im#M7ZD2Ja7w@PxR"},
		{"mega timpanoid", "ar&DJWkvs4b4Im#M7ZD2Fa&w@PER"},
		{"timpanoid", "HrcIx#2e@V3r5iRBvE%YPBXWMMxa"},
		{"tall timpanoid", "zVe6QvVULEQmexj5fXjDeCv2qzlu"},
		{"mini dekkoid", "AwrQkxaPwT#9dt8YK#YzIBKXGCA2"},
		{"mega dekkoid", "pr&DJk%vs4biIm#M7ZD2Fa&3@PER"},
		{"dekkoid", "HrcIx#2e@V3r5iRBvE%YPBXWMMx2"},
		{"mini drilloid", "5g96QaVNLEIAtxa5fXj@gCv2dzlu"},
		{"mega drilloid", "fapCIuxyxELs#AOh6n#4rDGOKTn@"},
		{"drilloid", "fapCpXAhxqsw#AOs6n#4rDGOKTnv"},
		{"mega oboid", "fapCpuxhxv4s#AOh6o#4r@GOKTn@"},
		{"oboid", "zV96QvVULEQDexjrfXuDe9v2aKlu"},
		{"tall oboid", "#g96QvVNLqI4exa5fXj@emv2dzqu"},
		{"mini clankoid", "AwrQkxaPuT#9dt8YK#YzIB8XGCA2"},
		{"mega clankoid", "X5JQC#Pg8R%gKYUqKjqjoR#uJbQ2"},
		{"clankoid", "X5JQC#Pg8R%gKYUqKjqjoRiuJbQa"},
		{"tall clankoid", "HrqIx#2eDx3r5iRBvE%jPVhWMMx2"},
		{"mini alloid", "ar&DJWkvw4b4IF#M7ZD2Fa&w@PER"},
		{"mega alloid", "aL&DJWkvwob4IF#M7Z@WOj8w@#xR"},
		{"tall alloid", "pr&DJk%vs4biIm#M7ZD2FlR3@PER"},
		{"mini dinkoid", "JTmu7GJH3Eo#FYxD2ynaCx#PaWge"},
		{"mega dinkoid", "JTmu7GJH3Eo#FYxDpynaCxePaWge"},
		{"tall droploid", "J5EDpx2Uie%@6jKOUd3h&zixAIEW"},
		{"mini harmonoid", "TapCpXAhxELw#AOG6n#4UDwOKTlv"},
		{"mega harmonoid", "TaHCpXxhxqss#AOy6n#4UDwOKTl@"},
		{"harmonoid", "#g96QvVNLEQ4exa5fXj@emv2dzqu"},
		{"tall harmonoid", "TaHCIuAyxqsw#AOG6n#4UDwOKTlv"},
		{"mini tootoid", "HrqIx#2e@x3r5iRBvE%jPVyfMMx2"},
		{"mega tootoid", "aL&DJWkvwob4IF#M7Z@WOB4w@#xR"},
		{"tootoid", "pL&DJk%vsobiIF#M7Z@WOj83@#xR"},
		{"mini howloid", "fapCpXxhxEss#AOh6n#4rDGOKTn@"},
		{"mega howloid", "rg96QaVNLqILtxarfXu@gIv2Kzqu"},
		{"howloid", "TaHCINxyxvRs#AOy6o#4U@wOKTl@"},
		{"mini bowtoid", "HrcIx#2e@V3r5iRBvE%YPV5fMMxa"},
		{"mega bowtoid", "Aw#QkxaPwj#9dt8YK#YtIBqXGCA2"},
		{"bowtoid", "Aw#QkxaPwj#9dt8YK#YtIV%XGCA2"},
		{"tall bowtoid", "pL&D9k%fsobiIm#M7Z@WZB83@#ER"},
		{"mini nebuloid", "faHCpuxhxlLs#AOh6o#4r@GOKTn@"},
		{"mega nebuloid", "fapCpuxhxlLs#AOh6o#4r@GOKTn@"},
		{"squat nebuloid", "zg96QvVNLEQQexarfXu@e9v2Kzlu"},
		{"nebuloid", "fapCpXxhxqss#AOh6n#4rDGOKTn@"},
		{"tall nebuloid", "zV96QvVULEQmexj5fXjDeCv2qzlu"},
		{"slim nebuloid", "TapCpuAhxlLw#AOG6o#4U@wOKTlv"},
		{"wee dingloid", "Aw#QkxaPuj#9dt8YK#YtIVqXGCA2"},
		{"mini dingloid", "aL&D9Wkfsob4Im#M7Z@WZB8w@#xR"},
		{"mega dingloid", "pr&D9k%fw4biIF#M7ZD2Jl&3@PER"},
		{"squat dingloid", "HrcIx#2eDV3r5iRBvE%YPV5fMMx2"},
		{"dingloid", "J5xDpx2U##%@6jKOUd3J&zjxAIEf"},
		{"tall dingloid", "J5EDpx2Uie%@6jKOUd3h&zixAIEf"},
		{"mini puffoid", "fapCIuAyxqLw#AOs6n#4rDGOKTnv"},
		{"mega puffoid", "TaHCpXxhxEss#AOy6n#4UDwOKTl@"},
		{"tall puffoid", "rge6QaVNLEILtxarfXu@gIv2Kzqu"},
		{"mini lullaboid", "faHCpXxhxqss#AOh6n#4rDGOKTn@"},
		{"mega lullaboid", "TapCINxyxlss#AOy6o#4U@wOKTl@"},
		{"lullaboid", "fapCpuAhxvRw#AOs6o#4r@GOKTnv"},
		{"tall lullaboid", "zVe6QvVULEIDexjrfXuDe9v2aKlu"},
		{"mega percoloid", "fapCINxyxv4s#AOh6o#4r@GOKTn@"},
		{"tall percoloid", "5g96QaVNLEQQtxarfXu@g9v2Kzlu"},
		{"mini sproid", "pL&D9k%fwobiIF#M7Z@WZB83@#xR"},
		{"mega sproid", "J5xDpx2Ui#%@6jKOUd3J&#BMAIEW"},
		{"sproid", "pr&DJk%vs4biIF#M7ZD2Fa&3@PER"},
		{"tall sproid", "pr&D9k%fs4biIm#M7ZD2Ja73@PER"},
		{"mini rhythmoid", "zge6QvVNLqQAexa5fXj@eCv2dzlu"},
		{"rhythmoid", "TapCpuxhxlLs#AOy6o#4U@wOKTl@"},
		{"mini oombloid", "lEskIWCWWD2OUapXV3Am@s4tRO2i"},
		{"mega oombloid", "JTmu&GJ43EuiFYxmSynaCxeIaWge"},
		{"oombloid", "lEskrWOfWD2ONSpfB3km9sAt&Fpi"},
		{"tall oombloid", "JTmu7GJH3Eo#FYxDHynaCxePaWge"},
		{"mega bovoid", "aL&D9Wkfsob4IF#M7Z@WZB8w@#xR"},
		{"tall bovoid", "X5TQC#PgUx%gKYUqKjqYoRxuJbQ2"},
		{"mini sputnoid", "lEskrWCWWD2ONSpfB3km9sAt&Fpi"},
		{"mega sputnoid", "JTmuEMp43fuiFYxmSynaCx#PaWge"},
		{"sputnoid", "JTmuEZ243JuiFYxmeynaCRVPaWge"},
		{"tall sputnoid", "JTmu7GJH3Eo#FYxDpynaCxeIaWge"},
		{"mini quazoid", "HrqIx#2eDx3r5iRBvE%jPByfMMx2"},
		{"mega quazoid", "pL&DJk%vwobiIm#M7Z@WOj83@#ER"},
		{"quazoid", "X5TQC#PgUx%gKYUqKjqYoRTuJbQ2"},
		{"tall quazoid", "pr&D9k%fs4biIF#M7ZD2Jl&3@PER"},
		{"slim quazoid", "#g96QvVNLEI4exa5fXj@emv2dzqu"},

		// Fossils
		{"tricera skull", "rg96QaVNLEQLtxhrfXw@gIv2Kzqu"},
		{"tricera torso", "TaHCpuAhxvRw#AtG6o44U@wOKTlv"},
		{"tricera tail", "#V96QvVULqQ%exurfXwDeIv2aKqu"},
		{"t-rex skull", "zg96QvVNLEIQexhrfXw@e9v2Kzlu"},
		{"t-rex torso", "eCb7l%UdQSXkrIkoqHQdQtfyDoy8"},
		{"t-rex tail", "zVe6QvVULEQDexurfXwDe9v2aKlu"},
		{"apato skull", "rOHmy%b6LW3&UGMZDoOKnPxdEvho"},
		{"apato torso", "gu#P3V&uu9UcBzvMd8J7sUv7#DTf"},
		{"apato tail", "Wb5Q%Y&VxQNZnYlCAlsowl7JRvpF"},
		{"stego skull", "rOimy%b6Lf3&UVMZDoOKlPxdEvho"},
		{"stego torso", "gu#P3i&uu6UcBzvZd8Sws&v7#DTf"},
		{"stego tail", "Wb5Q%t&VxJuZnYlOAl8kw87JRvpF"},
		{"ptera skull", "eCb7l%UdQSXkrPkolHQdQtfyDoy8"},
		{"ptera right wing", "gu#PWN&wg5UcBzv5d8Nww&vg#DTf"},
		{"ptera left wing", "rOHmy%b6LW3&UGMZDoObBPxdEvhu"},
		{"plesio skull", "gu#PkV&ugrUcBzvMd8h7w&vg#DTf"},
		{"plesio neck", "eCb7l%UdIKWkrIkolFQKQtfy%oy8"},
		{"plesio torso", "nN#PcV&wu9UcBzvrt8JwsUv7#Djf"},
		{"mammoth skull", "kb5QEY&VesNZnYlC%lQosl7MRvXF"},
		{"mammoth torso", "rOHmy%b6yg3&UGMZU4OdnPxd@vho"},
		{"amber", "eCO7l%UdIbWkrIkoqFQKAtfy%oy8"},
		{"dinosaur track", "rOHmy%b6yg3&UVMZU4OOBPxd@vhu"},
		{"ammonite", "gu#PWv&wgrUcBzvrd8hww&vg#DTf"},
		{"dinosaur egg", "rOimy%b6yv3&UVMZU4OdlPxd@vho"},
		{"trilobite", "Wb5Qfq&RxQNZnYl3Alskwl7JRvpF"},

		// Music
		{"k.k. chorale", "l2RuzQ2Whgs%&jBAmn8zZ5INTDDp"},
		{"k.k. march", "AMjThT7j#bwbZzwQ&2U6TsZcvP@k"},
		{"k.k. waltz", "d7RWzQ2ch@s%&jBAmnUBZ5INFDDp"},
		{"k.k. swing", "2Zo23MVnJxHs%xMkwon8irpvYA2k"},
		{"k.k. jazz", "AMjThj7V#bwbZzwQ&2UyTrdbvId%"},
		{"k.k. fusion", "TQhThq&H#bwKZzwQ&2N5Es6kGP@k"},
		{"k.k. etude", "pGs2mij2bKGbqxG%RucdV5j@EQpk"},
		{"k.k. lullaby", "d3RWzs2kjvs%&jYAmnUBZ5INSDP6"},
		{"k.k. aria", "dnRuzQggh@Q%&jBAknUtY5INFUDp"},
		{"k.k. samba", "b7oF3QG2FEHh%xGkwo2Oisav5AIc"},
		{"k.k. bossa", "l2RWzMg2hCs%&jBAkn8zZ5INTDDp"},
		{"k.k. calypso", "bWo23JjkJUis%xMk3o2OXrpvcB2k"},
		{"k.k. salsa", "d7RuzMgghvs%&jBAknUBZ5INFDDp"},
		{"k.k. mambo", "dnRuzh2ch@Qf&jBAmnUtYh7NFUSH"},
		{"k.k. reggae", "Iys2m5hbbqGhqxG%RuWoj5H@rQpk"},
		{"k.k. ska", "AyhHhT7lUcwbZzCQ&2N5xrqboIdq"},
		{"k.k. tango", "bgoF3GjWFUis%xGk3o2nXrpv5Bpc"},
		{"k.k. faire", "IhRFm9jbbKGhqxG%RuWkhhJ&rAIk"},
		{"aloha k.k.", "AZhHhB&j#cwbZzwQ&2NZxrlbGId%"},
		{"lucky k.k.", "TGjHhf7dUbwKZzCQ&2U6TrKbBIdq"},
		{"k.k. condor", "2hsF3hVgFxHs%xGkwon%irpvqApc"},
		{"k.k. steppe", "dnRuzhg2hvQf&jBAknUBYh7NFUSH"},
		{"imperial k.k.", "b7o23hV2FEHs%xGkwo2nirpv5Apc"},
		{"k.k. casbah", "dkRWzy2kjvQ%&jYAmnUtY5INSUP6"},
		{"k.k. safari", "TQhTha7e#bwKZzwQ&2N5ErloGId%"},
		{"k.k. folk", "TZhThq&H#cwKZzwQ&2N5xs6cGP@k"},
		{"k.k. rock", "phR2mzh2bKGbqxG%RuWkh5HDrQpk"},
		{"rockin' k.k.", "lWRWzs2kjCQ%&jYAmn8zY5INJUP6"},
		{"k.k. ragtime", "pysFmzhgbqGbqxG%RuWkj5H@rQpk"},
		{"k.k. gumbo", "d7RuzGg2hvsf&jBAknUtZh7NFDSH"},
		{"the k. funk", "2hs23GjcFxHs%xGk3on%irpvqApc"},
		{"k.k. blues", "bWo23JVnJUis%xMkwo2OXrpvcB2k"},
		{"soulful k.k.", "d7RuzM2Wh@s%&jBAmnUtZ5INFDDp"},
		{"k.k. soul", "2hsF3ZhcF#Hh%xGk3on8isavqAIc"},
		{"k.k. cruisin'", "b7o23hjcFEHs%xGk3o2Oirpv5Apc"},
		{"k.k. love song", "pJs2mHj6hbGbqxM%RucdV5T@YQpc"},
		{"k.k. d & b", "AJjThj7V#bwbZzwQ&2U6frdovId%"},
		{"k.k. technopop", "IssFm9jbbKGhqxG%RuclGhp&EAIk"},
		{"dj k.k.", "TZhHha7H#bwKZzwQ&2N5xrlbGId%"},
		{"only me", "lWRWzs2kjCQ%&jYAmn8YY5INJUP6"},
		{"k.k. country", "TQhThl&e#bwKZzwQ&2NZErloGId%"},
		{"surfin' k.k.", "2yoF3ZG2F#ih%xGkwon%XsavqBIc"},
		{"k.k. ballad", "lgRWzMg2hCQ%&jBAkn8YY5INTUDp"},
		{"comrade k.k.", "bWo23JVnJEis%xMkwo2OXrpvcB2k"},
		{"k.k. lament", "l2RuzM2WhCs%&jBAmn8zZ5INTDDp"},
		{"go k.k. rider!", "2yoF3QhcFxih%xGk3on8XsavqBIc"},
		{"k.k. dirge", "Iys2mXjbbKGhqxG%RuWkj5H@rQpk"},
		{"k.k. western", "d3RWzy2kjvs%&jYAmnUBZ5INSDP6"},
		{"mr. k.k.", "pssFmzhgbqGbqxG%RuclG5jDEQpk"},
		{"cafe k.k.", "AQhThY&j#bwbZzwQ&2NZEs6kGP@k"},
		{"k.k. parade", "TMjHha7H#cwKZzwQ&2U6TrdbvId%"},
		{"senor k.k.", "IMs2mpjyhcGhqxM%RucdG5TDYQpc"},
		{"k.k. song", "2yoF3hVgF#is%xGkwon%XrpvqBpc"},
		{"i love you", "lgRuzh2chgQf&jBAmn8zYh7NTUSH"},
		{"two days ago", "pss2mij2bqGbqxG%RucdG5jDEQpk"},

		// Other Items
		{"1,000 bells", "lcVA6IZbjQ2fFSFbUtRz6OfYCv5h"},
		{"10,000 bells", "5cVAZIZ5jocAmSFurtRt6OTzCv6s"},
		{"30,000 bells", "#&RjVnP6LpRO2R#r5iqZB8@cX5CX"},
		{"100 bells", "uEcNw4YRcfjK3k&s#Be7nT%tKWpO"},
		{"videotape", "bxcNw4xacWBz3oIszBe7oj&dKWpt"},
		{"organizer", "5YVAZsQbPkbjOK8NEtRz6OWYCgqr"},
		{"pokémon pikachu", "vEfKxfIk%jbz3izUrtT8xoDH5bSD"},
		{"comic book", "vMaKxf&kPBbK3ez&rtT838DHpXF%"},
		{"picture book", "OxbNw4xacHlz3o6szB#IBj&dqWpt"},
		{"game boy", "vMaKxW&k%BbY3ez&rYT87oD25uFD"},
		{"camera", "qYVA6sQ5P%bRmK%NMtRt6CWzCglr"},
		{"watch", "6YVAZsQbPkuaCKNbEtRt6nWjmgK5"},
		{"handkerchief", "icT87f9bWTF%%EuT@wZaBgevaHh7"},
		{"glasses case", "vEaKxS&kABbz3ezartW8PoDH5uFD"},
		{"empty can", "lYVA6IQjPkWaCK8KUtRt6nfYmgq5"},
		{"boot", "OxcNw4xacWBz3oIszBe7oj&dKWpt"},
		{"old tire", "6YVAZIQhPkcjOKNuUtRz6OfYCgqr"},
		{"fossil", "5YVAZsQcP%bjmK%NMtRt6CXzCglr"},
		{"pitfall", "vMaKxF&kABbq3ezarYT838D25CFD"},
		{"lions paw", "vEaKxS&nABcz3tzaLtW87oDH5uFD"},
		{"wentletrap", "vEfKxSIkAjbz3izKrtW8CoDH5bSD"},
		{"venus comb", "qYVA6sQjPkbjOKNuEtRt6nWYmgqr"},
		{"porceletta", "bxbNw4xacTBz3o6szBe7Bj&8qWpt"},
		{"sand dollar", "vEaKxW&k%BbY3ez&rYT8PoD25uFD"},
		{"white scallop", "vEfKxSIk%jbz3izKrtW8CoDH5bSD"},
		{"conch", "5YVAZIQbPkcjOK8NUtRt6nfjmgKr"},
		{"coral", "3gYoDND4@HDk8@4NkbZjCsLuSehU"},
		{"present", "lYVA6IQhPkcROK8NUtRz6OfYCgqr"},
		{"sign board", "vEaKxF&nPBcq3tzaLYT8#8D25CFD"},
		{"exercise card", "wEbNw4xacWBz3oIUzBe2oj&d8FpY"},
		{"knife and fork", "vMaKxF&nPBcY3tzaLYW8PoD25uFD"},
		{"apple", "C&3Tcr4kRaef%udelC2hqoDRKjjx"},
		{"cherry", "eai3hy6&ylXTtPkjfXCReaeztsJm"},
		{"pear", "ZdOLwsMlPrxJ8%3Ztx7DetRYU5Mk"},
		{"peach", "C&3Tcr4lj2ef%udeqg2pfLDjKRRx"},
		{"orange", "RhGRWkaTSaNKcMi%BxP7lHSzfzrf"},
		{"mushroom", "ZdOLwyElPsAJ8%3Ztx7DeOPAU5Mk"},
		{"candy", "ZdOLwsMlPrAJ8%3Ztx7DeORYU5Mk"},
		{"coconut", "C&3Tcr4lj2ef%udelg2pqoDRKRRx"},
		{"sapling", "xarTcr4kRhef%uqelC2hqoDRKXjx"},
		{"cedar sapling", "tE5xBgBks8f2BPYZ5mPe7VEc49M%"},
		{"white pansy bag", "ZdOLmsMlPrxJ883Ztx7DetAYK5Mc"},
		{"purple pansy bag", "xarTcr4ljjef%uqeqg2pfLDjKLRx"},
		{"yellow pansy bag", "RhGRWkaxSaNKcMiDBxPIlHSzfzrf"},
		{"white cosmos bag", "ZdOLmyElPsAJ883Ztx7DeO4AK5Mc"},
		{"pink cosmos bag", "ZdOLmsMlPrAJ883Ztx7DeOAYK5Mc"},
		{"blue cosmos bag", "xarTcr4ljjef%uqelg2pqoDRKLRx"},
		{"red tulip bag", "RhGRWkaxSaNKcMiDoxPI%HSzfzGf"},
		{"white tulip bag", "e&i3hy97ylhTtPkjfXCRea#ztsJm"},
		{"yellow tulip bag", "ZdOLmyMlPrAJ883Ztx7DetAmK5Mc"},
		{"january ticket", "MAzI7ydn7Yrv@Q7ijbyP7oqPegOe"},
		{"february ticket", "MQ5Ikydn7YGv@QnBjbdP7ocHYgO#"},
		{"march ticket", "MQzIPydn7Yrv@Q74jbyPgocPtgOe"},
		{"april ticket", "@PYImZdBRYwv@QgvY5dP7ncHYgA#"},
		{"may ticket", "MQzIkydn7Yrv@QnBjblP7ocIYgOe"},
		{"june ticket", "@PYImZdBRYwv@QgvY5dPgncpYgA#"},
		{"july ticket", "@AZIkZdB7Ywv@QgvY5lPgoqpxgA#"},
		{"august ticket", "@AZIkZdB7cwv@Q2vY56PgoKpxgA#"},
		{"september ticket", "MAzI7ydn7Yrv@Q7ijb6PgoqIegOe"},
		{"october ticket", "MAzI7ydn7Yrv@Q7ijbyPgoqIegOe"},
		{"november ticket", "MQ5I4ydn7YGv@QnBjbdPgocHYgO#"},
		{"december ticket", "MA5I4ydn7YGv@QnVjblP7oqHxgO#"},
		{"grab bag", "MAzIwyd2kAr9@Q7iYKyP7ocPtgFE"},
		{"10 turnips", "Watu9ufP6w@etj#YU%FmctoJiB8i"},
		{"50 turnips", "iblu9oKonbPiPT3xUlDfrHRwiq8T"},
		{"100 turnips", "WatuXufm6uC#tcrYU%Fm5DLGiYfl"},
		{"spoiled turnips", "Z8&vJufAT9ENzkfBJEeUVqs%edEV"},
	};

	const size_t codes_count = sizeof(codes) / sizeof(codes[0]);

	inline const char* find_code(const char* name) {
		for(size_t i = 0; i < codes_count; i++) {
			if(strcmp(codes[i].name, name) == 0) {
				return codes[i].code;
			}
		}
		return nullptr;
	}
	
	// Public interface functions
	// Check if currently in nook code mode
	bool isInNookCodeMode();
	
	// Check if backspace is needed
	bool needsBackspace();
	
	// Check if buffer should be cleared
	bool shouldClearBuffer();
	
	// Check if START button should be pressed
	bool shouldPressStart();
	
	// Clear the need to clear buffer flag
	void clearNeedToClearBuffer();
	
	// Clear the need to press START flag
	void clearNeedToPressStart();
	
	// Get reference to the item name
	std::vector<Utf8Char>& getItemName();
	
	// Enter nook code mode
	void enterNookCodeMode();
	
	// Exit nook code mode
	void exitNookCodeMode();
	
	// Process backspace in nook code mode
	bool processBackspace();
	
	// Add a character to the item name
	void addCharToItemName(const Utf8Char& c);
	
	// Check and process nook code
	bool checkAndProcessNookCode();
}